// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/map_outer.proto

package mapouterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Float3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Float3) Reset() {
	*x = Float3{}
	mi := &file_proto_map_outer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Float3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float3) ProtoMessage() {}

func (x *Float3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float3.ProtoReflect.Descriptor instead.
func (*Float3) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{0}
}

func (x *Float3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Float3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Float3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Quaternion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
	W             float32                `protobuf:"fixed32,4,opt,name=W,proto3" json:"W,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quaternion) Reset() {
	*x = Quaternion{}
	mi := &file_proto_map_outer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quaternion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quaternion) ProtoMessage() {}

func (x *Quaternion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quaternion.ProtoReflect.Descriptor instead.
func (*Quaternion) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{1}
}

func (x *Quaternion) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Quaternion) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Quaternion) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Quaternion) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

type MoveInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Float3              `protobuf:"bytes,1,rep,name=Points,proto3" json:"Points,omitempty"`
	Rotation      *Quaternion            `protobuf:"bytes,2,opt,name=Rotation,proto3" json:"Rotation,omitempty"`
	TurnSpeed     int32                  `protobuf:"varint,3,opt,name=TurnSpeed,proto3" json:"TurnSpeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveInfo) Reset() {
	*x = MoveInfo{}
	mi := &file_proto_map_outer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveInfo) ProtoMessage() {}

func (x *MoveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveInfo.ProtoReflect.Descriptor instead.
func (*MoveInfo) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{2}
}

func (x *MoveInfo) GetPoints() []*Float3 {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *MoveInfo) GetRotation() *Quaternion {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *MoveInfo) GetTurnSpeed() int32 {
	if x != nil {
		return x.TurnSpeed
	}
	return 0
}

type UnitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitId        int64                  `protobuf:"varint,1,opt,name=UnitId,proto3" json:"UnitId,omitempty"`
	ConfigId      int32                  `protobuf:"varint,2,opt,name=ConfigId,proto3" json:"ConfigId,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Position      *Float3                `protobuf:"bytes,4,opt,name=Position,proto3" json:"Position,omitempty"`
	Forward       *Float3                `protobuf:"bytes,5,opt,name=Forward,proto3" json:"Forward,omitempty"`
	KV            map[int32]int64        `protobuf:"bytes,6,rep,name=KV,proto3" json:"KV,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MoveInfo      *MoveInfo              `protobuf:"bytes,7,opt,name=MoveInfo,proto3" json:"MoveInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitInfo) Reset() {
	*x = UnitInfo{}
	mi := &file_proto_map_outer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitInfo) ProtoMessage() {}

func (x *UnitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitInfo.ProtoReflect.Descriptor instead.
func (*UnitInfo) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{3}
}

func (x *UnitInfo) GetUnitId() int64 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *UnitInfo) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *UnitInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UnitInfo) GetPosition() *Float3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *UnitInfo) GetForward() *Float3 {
	if x != nil {
		return x.Forward
	}
	return nil
}

func (x *UnitInfo) GetKV() map[int32]int64 {
	if x != nil {
		return x.KV
	}
	return nil
}

func (x *UnitInfo) GetMoveInfo() *MoveInfo {
	if x != nil {
		return x.MoveInfo
	}
	return nil
}

type C2M_TransferMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2M_TransferMap) Reset() {
	*x = C2M_TransferMap{}
	mi := &file_proto_map_outer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2M_TransferMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2M_TransferMap) ProtoMessage() {}

func (x *C2M_TransferMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2M_TransferMap.ProtoReflect.Descriptor instead.
func (*C2M_TransferMap) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{4}
}

func (x *C2M_TransferMap) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

type M2C_TransferMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2C_TransferMap) Reset() {
	*x = M2C_TransferMap{}
	mi := &file_proto_map_outer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_TransferMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_TransferMap) ProtoMessage() {}

func (x *M2C_TransferMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_TransferMap.ProtoReflect.Descriptor instead.
func (*M2C_TransferMap) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{5}
}

func (x *M2C_TransferMap) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *M2C_TransferMap) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *M2C_TransferMap) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type C2M_EnterMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2M_EnterMap) Reset() {
	*x = C2M_EnterMap{}
	mi := &file_proto_map_outer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2M_EnterMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2M_EnterMap) ProtoMessage() {}

func (x *C2M_EnterMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2M_EnterMap.ProtoReflect.Descriptor instead.
func (*C2M_EnterMap) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{6}
}

func (x *C2M_EnterMap) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

type M2C_EnterMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2C_EnterMap) Reset() {
	*x = M2C_EnterMap{}
	mi := &file_proto_map_outer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_EnterMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_EnterMap) ProtoMessage() {}

func (x *M2C_EnterMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_EnterMap.ProtoReflect.Descriptor instead.
func (*M2C_EnterMap) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{7}
}

func (x *M2C_EnterMap) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *M2C_EnterMap) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *M2C_EnterMap) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type M2C_CreateUnits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*UnitInfo            `protobuf:"bytes,1,rep,name=Units,proto3" json:"Units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2C_CreateUnits) Reset() {
	*x = M2C_CreateUnits{}
	mi := &file_proto_map_outer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_CreateUnits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_CreateUnits) ProtoMessage() {}

func (x *M2C_CreateUnits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_CreateUnits.ProtoReflect.Descriptor instead.
func (*M2C_CreateUnits) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{8}
}

func (x *M2C_CreateUnits) GetUnits() []*UnitInfo {
	if x != nil {
		return x.Units
	}
	return nil
}

type M2C_CreateMyUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          *UnitInfo              `protobuf:"bytes,1,opt,name=Unit,proto3" json:"Unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2C_CreateMyUnit) Reset() {
	*x = M2C_CreateMyUnit{}
	mi := &file_proto_map_outer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_CreateMyUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_CreateMyUnit) ProtoMessage() {}

func (x *M2C_CreateMyUnit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_CreateMyUnit.ProtoReflect.Descriptor instead.
func (*M2C_CreateMyUnit) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{9}
}

func (x *M2C_CreateMyUnit) GetUnit() *UnitInfo {
	if x != nil {
		return x.Unit
	}
	return nil
}

type M2C_RemoveUnits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []int64                `protobuf:"varint,1,rep,packed,name=Units,proto3" json:"Units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2C_RemoveUnits) Reset() {
	*x = M2C_RemoveUnits{}
	mi := &file_proto_map_outer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_RemoveUnits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_RemoveUnits) ProtoMessage() {}

func (x *M2C_RemoveUnits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_RemoveUnits.ProtoReflect.Descriptor instead.
func (*M2C_RemoveUnits) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{10}
}

func (x *M2C_RemoveUnits) GetUnits() []int64 {
	if x != nil {
		return x.Units
	}
	return nil
}

type M2C_StartSceneChange struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SceneInstanceId int64                  `protobuf:"varint,1,opt,name=SceneInstanceId,proto3" json:"SceneInstanceId,omitempty"`
	SceneName       string                 `protobuf:"bytes,2,opt,name=SceneName,proto3" json:"SceneName,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *M2C_StartSceneChange) Reset() {
	*x = M2C_StartSceneChange{}
	mi := &file_proto_map_outer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_StartSceneChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_StartSceneChange) ProtoMessage() {}

func (x *M2C_StartSceneChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_StartSceneChange.ProtoReflect.Descriptor instead.
func (*M2C_StartSceneChange) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{11}
}

func (x *M2C_StartSceneChange) GetSceneInstanceId() int64 {
	if x != nil {
		return x.SceneInstanceId
	}
	return 0
}

func (x *M2C_StartSceneChange) GetSceneName() string {
	if x != nil {
		return x.SceneName
	}
	return ""
}

type C2M_PathfindingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Position      *Float3                `protobuf:"bytes,2,opt,name=Position,proto3" json:"Position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2M_PathfindingResult) Reset() {
	*x = C2M_PathfindingResult{}
	mi := &file_proto_map_outer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2M_PathfindingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2M_PathfindingResult) ProtoMessage() {}

func (x *C2M_PathfindingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2M_PathfindingResult.ProtoReflect.Descriptor instead.
func (*C2M_PathfindingResult) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{12}
}

func (x *C2M_PathfindingResult) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *C2M_PathfindingResult) GetPosition() *Float3 {
	if x != nil {
		return x.Position
	}
	return nil
}

type C2M_Stop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2M_Stop) Reset() {
	*x = C2M_Stop{}
	mi := &file_proto_map_outer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2M_Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2M_Stop) ProtoMessage() {}

func (x *C2M_Stop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2M_Stop.ProtoReflect.Descriptor instead.
func (*C2M_Stop) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{13}
}

func (x *C2M_Stop) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

type M2C_PathfindingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Position      *Float3                `protobuf:"bytes,2,opt,name=Position,proto3" json:"Position,omitempty"`
	Points        []*Float3              `protobuf:"bytes,3,rep,name=Points,proto3" json:"Points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2C_PathfindingResult) Reset() {
	*x = M2C_PathfindingResult{}
	mi := &file_proto_map_outer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_PathfindingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_PathfindingResult) ProtoMessage() {}

func (x *M2C_PathfindingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_PathfindingResult.ProtoReflect.Descriptor instead.
func (*M2C_PathfindingResult) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{14}
}

func (x *M2C_PathfindingResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *M2C_PathfindingResult) GetPosition() *Float3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *M2C_PathfindingResult) GetPoints() []*Float3 {
	if x != nil {
		return x.Points
	}
	return nil
}

type M2C_Stop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         int32                  `protobuf:"varint,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Position      *Float3                `protobuf:"bytes,3,opt,name=Position,proto3" json:"Position,omitempty"`
	Rotation      *Quaternion            `protobuf:"bytes,4,opt,name=Rotation,proto3" json:"Rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2C_Stop) Reset() {
	*x = M2C_Stop{}
	mi := &file_proto_map_outer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_Stop) ProtoMessage() {}

func (x *M2C_Stop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_outer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_Stop.ProtoReflect.Descriptor instead.
func (*M2C_Stop) Descriptor() ([]byte, []int) {
	return file_proto_map_outer_proto_rawDescGZIP(), []int{15}
}

func (x *M2C_Stop) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *M2C_Stop) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *M2C_Stop) GetPosition() *Float3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *M2C_Stop) GetRotation() *Quaternion {
	if x != nil {
		return x.Rotation
	}
	return nil
}

var File_proto_map_outer_proto protoreflect.FileDescriptor

const file_proto_map_outer_proto_rawDesc = "" +
	"\n" +
	"\x15proto/map_outer.proto\x12\x05proto\"2\n" +
	"\x06Float3\x12\f\n" +
	"\x01X\x18\x01 \x01(\x02R\x01X\x12\f\n" +
	"\x01Y\x18\x02 \x01(\x02R\x01Y\x12\f\n" +
	"\x01Z\x18\x03 \x01(\x02R\x01Z\"D\n" +
	"\n" +
	"Quaternion\x12\f\n" +
	"\x01X\x18\x01 \x01(\x02R\x01X\x12\f\n" +
	"\x01Y\x18\x02 \x01(\x02R\x01Y\x12\f\n" +
	"\x01Z\x18\x03 \x01(\x02R\x01Z\x12\f\n" +
	"\x01W\x18\x04 \x01(\x02R\x01W\"~\n" +
	"\bMoveInfo\x12%\n" +
	"\x06Points\x18\x01 \x03(\v2\r.proto.Float3R\x06Points\x12-\n" +
	"\bRotation\x18\x02 \x01(\v2\x11.proto.QuaternionR\bRotation\x12\x1c\n" +
	"\tTurnSpeed\x18\x03 \x01(\x05R\tTurnSpeed\"\xb3\x02\n" +
	"\bUnitInfo\x12\x16\n" +
	"\x06UnitId\x18\x01 \x01(\x03R\x06UnitId\x12\x1a\n" +
	"\bConfigId\x18\x02 \x01(\x05R\bConfigId\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\x05R\x04Type\x12)\n" +
	"\bPosition\x18\x04 \x01(\v2\r.proto.Float3R\bPosition\x12'\n" +
	"\aForward\x18\x05 \x01(\v2\r.proto.Float3R\aForward\x12'\n" +
	"\x02KV\x18\x06 \x03(\v2\x17.proto.UnitInfo.KVEntryR\x02KV\x12+\n" +
	"\bMoveInfo\x18\a \x01(\v2\x0f.proto.MoveInfoR\bMoveInfo\x1a5\n" +
	"\aKVEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"'\n" +
	"\x0fC2M_TransferMap\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\"W\n" +
	"\x0fM2C_TransferMap\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\"$\n" +
	"\fC2M_EnterMap\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\"T\n" +
	"\fM2C_EnterMap\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\"8\n" +
	"\x0fM2C_CreateUnits\x12%\n" +
	"\x05Units\x18\x01 \x03(\v2\x0f.proto.UnitInfoR\x05Units\"7\n" +
	"\x10M2C_CreateMyUnit\x12#\n" +
	"\x04Unit\x18\x01 \x01(\v2\x0f.proto.UnitInfoR\x04Unit\"'\n" +
	"\x0fM2C_RemoveUnits\x12\x14\n" +
	"\x05Units\x18\x01 \x03(\x03R\x05Units\"^\n" +
	"\x14M2C_StartSceneChange\x12(\n" +
	"\x0fSceneInstanceId\x18\x01 \x01(\x03R\x0fSceneInstanceId\x12\x1c\n" +
	"\tSceneName\x18\x02 \x01(\tR\tSceneName\"X\n" +
	"\x15C2M_PathfindingResult\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12)\n" +
	"\bPosition\x18\x02 \x01(\v2\r.proto.Float3R\bPosition\" \n" +
	"\bC2M_Stop\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\"y\n" +
	"\x15M2C_PathfindingResult\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12)\n" +
	"\bPosition\x18\x02 \x01(\v2\r.proto.Float3R\bPosition\x12%\n" +
	"\x06Points\x18\x03 \x03(\v2\r.proto.Float3R\x06Points\"\x8a\x01\n" +
	"\bM2C_Stop\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\x05R\x05Error\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\x03R\x02Id\x12)\n" +
	"\bPosition\x18\x03 \x01(\v2\r.proto.Float3R\bPosition\x12-\n" +
	"\bRotation\x18\x04 \x01(\v2\x11.proto.QuaternionR\bRotationB4Z2github.com/jerbe/et-go/proto/mapouterpb;mapouterpbb\x06proto3"

var (
	file_proto_map_outer_proto_rawDescOnce sync.Once
	file_proto_map_outer_proto_rawDescData []byte
)

func file_proto_map_outer_proto_rawDescGZIP() []byte {
	file_proto_map_outer_proto_rawDescOnce.Do(func() {
		file_proto_map_outer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_map_outer_proto_rawDesc), len(file_proto_map_outer_proto_rawDesc)))
	})
	return file_proto_map_outer_proto_rawDescData
}

var file_proto_map_outer_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_map_outer_proto_goTypes = []any{
	(*Float3)(nil),                // 0: proto.Float3
	(*Quaternion)(nil),            // 1: proto.Quaternion
	(*MoveInfo)(nil),              // 2: proto.MoveInfo
	(*UnitInfo)(nil),              // 3: proto.UnitInfo
	(*C2M_TransferMap)(nil),       // 4: proto.C2M_TransferMap
	(*M2C_TransferMap)(nil),       // 5: proto.M2C_TransferMap
	(*C2M_EnterMap)(nil),          // 6: proto.C2M_EnterMap
	(*M2C_EnterMap)(nil),          // 7: proto.M2C_EnterMap
	(*M2C_CreateUnits)(nil),       // 8: proto.M2C_CreateUnits
	(*M2C_CreateMyUnit)(nil),      // 9: proto.M2C_CreateMyUnit
	(*M2C_RemoveUnits)(nil),       // 10: proto.M2C_RemoveUnits
	(*M2C_StartSceneChange)(nil),  // 11: proto.M2C_StartSceneChange
	(*C2M_PathfindingResult)(nil), // 12: proto.C2M_PathfindingResult
	(*C2M_Stop)(nil),              // 13: proto.C2M_Stop
	(*M2C_PathfindingResult)(nil), // 14: proto.M2C_PathfindingResult
	(*M2C_Stop)(nil),              // 15: proto.M2C_Stop
	nil,                           // 16: proto.UnitInfo.KVEntry
}
var file_proto_map_outer_proto_depIdxs = []int32{
	0,  // 0: proto.MoveInfo.Points:type_name -> proto.Float3
	1,  // 1: proto.MoveInfo.Rotation:type_name -> proto.Quaternion
	0,  // 2: proto.UnitInfo.Position:type_name -> proto.Float3
	0,  // 3: proto.UnitInfo.Forward:type_name -> proto.Float3
	16, // 4: proto.UnitInfo.KV:type_name -> proto.UnitInfo.KVEntry
	2,  // 5: proto.UnitInfo.MoveInfo:type_name -> proto.MoveInfo
	3,  // 6: proto.M2C_CreateUnits.Units:type_name -> proto.UnitInfo
	3,  // 7: proto.M2C_CreateMyUnit.Unit:type_name -> proto.UnitInfo
	0,  // 8: proto.C2M_PathfindingResult.Position:type_name -> proto.Float3
	0,  // 9: proto.M2C_PathfindingResult.Position:type_name -> proto.Float3
	0,  // 10: proto.M2C_PathfindingResult.Points:type_name -> proto.Float3
	0,  // 11: proto.M2C_Stop.Position:type_name -> proto.Float3
	1,  // 12: proto.M2C_Stop.Rotation:type_name -> proto.Quaternion
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_map_outer_proto_init() }
func file_proto_map_outer_proto_init() {
	if File_proto_map_outer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_map_outer_proto_rawDesc), len(file_proto_map_outer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_map_outer_proto_goTypes,
		DependencyIndexes: file_proto_map_outer_proto_depIdxs,
		MessageInfos:      file_proto_map_outer_proto_msgTypes,
	}.Build()
	File_proto_map_outer_proto = out.File
	file_proto_map_outer_proto_goTypes = nil
	file_proto_map_outer_proto_depIdxs = nil
}
