// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/actorlocation_inner.proto

package actorlocationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     int32                  `protobuf:"varint,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	FiberId       int64                  `protobuf:"varint,2,opt,name=fiber_id,json=fiberId,proto3" json:"fiber_id,omitempty"`
	InstanceId    int64                  `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorId) Reset() {
	*x = ActorId{}
	mi := &file_proto_actorlocation_inner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorId) ProtoMessage() {}

func (x *ActorId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actorlocation_inner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorId.ProtoReflect.Descriptor instead.
func (*ActorId) Descriptor() ([]byte, []int) {
	return file_proto_actorlocation_inner_proto_rawDescGZIP(), []int{0}
}

func (x *ActorId) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *ActorId) GetFiberId() int64 {
	if x != nil {
		return x.FiberId
	}
	return 0
}

func (x *ActorId) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type ObjectAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         int32                  `protobuf:"varint,1,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Key           int64                  `protobuf:"varint,3,opt,name=key,proto3" json:"key,omitempty"`
	ActorId       *ActorId               `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectAddRequest) Reset() {
	*x = ObjectAddRequest{}
	mi := &file_proto_actorlocation_inner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectAddRequest) ProtoMessage() {}

func (x *ObjectAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actorlocation_inner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectAddRequest.ProtoReflect.Descriptor instead.
func (*ObjectAddRequest) Descriptor() ([]byte, []int) {
	return file_proto_actorlocation_inner_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectAddRequest) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *ObjectAddRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ObjectAddRequest) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ObjectAddRequest) GetActorId() *ActorId {
	if x != nil {
		return x.ActorId
	}
	return nil
}

type ObjectAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         int32                  `protobuf:"varint,1,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectAddResponse) Reset() {
	*x = ObjectAddResponse{}
	mi := &file_proto_actorlocation_inner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectAddResponse) ProtoMessage() {}

func (x *ObjectAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actorlocation_inner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectAddResponse.ProtoReflect.Descriptor instead.
func (*ObjectAddResponse) Descriptor() ([]byte, []int) {
	return file_proto_actorlocation_inner_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectAddResponse) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *ObjectAddResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ObjectAddResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ObjectLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         int32                  `protobuf:"varint,1,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Key           int64                  `protobuf:"varint,3,opt,name=key,proto3" json:"key,omitempty"`
	ActorId       *ActorId               `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Time          int32                  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectLockRequest) Reset() {
	*x = ObjectLockRequest{}
	mi := &file_proto_actorlocation_inner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectLockRequest) ProtoMessage() {}

func (x *ObjectLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actorlocation_inner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectLockRequest.ProtoReflect.Descriptor instead.
func (*ObjectLockRequest) Descriptor() ([]byte, []int) {
	return file_proto_actorlocation_inner_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectLockRequest) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *ObjectLockRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ObjectLockRequest) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ObjectLockRequest) GetActorId() *ActorId {
	if x != nil {
		return x.ActorId
	}
	return nil
}

func (x *ObjectLockRequest) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ObjectLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         int32                  `protobuf:"varint,1,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectLockResponse) Reset() {
	*x = ObjectLockResponse{}
	mi := &file_proto_actorlocation_inner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectLockResponse) ProtoMessage() {}

func (x *ObjectLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actorlocation_inner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectLockResponse.ProtoReflect.Descriptor instead.
func (*ObjectLockResponse) Descriptor() ([]byte, []int) {
	return file_proto_actorlocation_inner_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectLockResponse) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *ObjectLockResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ObjectLockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ObjectUnLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         int32                  `protobuf:"varint,1,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Key           int64                  `protobuf:"varint,3,opt,name=key,proto3" json:"key,omitempty"`
	OldActorId    *ActorId               `protobuf:"bytes,4,opt,name=old_actor_id,json=oldActorId,proto3" json:"old_actor_id,omitempty"`
	NewActorId    *ActorId               `protobuf:"bytes,5,opt,name=new_actor_id,json=newActorId,proto3" json:"new_actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectUnLockRequest) Reset() {
	*x = ObjectUnLockRequest{}
	mi := &file_proto_actorlocation_inner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectUnLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectUnLockRequest) ProtoMessage() {}

func (x *ObjectUnLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actorlocation_inner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectUnLockRequest.ProtoReflect.Descriptor instead.
func (*ObjectUnLockRequest) Descriptor() ([]byte, []int) {
	return file_proto_actorlocation_inner_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectUnLockRequest) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *ObjectUnLockRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ObjectUnLockRequest) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ObjectUnLockRequest) GetOldActorId() *ActorId {
	if x != nil {
		return x.OldActorId
	}
	return nil
}

func (x *ObjectUnLockRequest) GetNewActorId() *ActorId {
	if x != nil {
		return x.NewActorId
	}
	return nil
}

type ObjectUnLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         int32                  `protobuf:"varint,1,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectUnLockResponse) Reset() {
	*x = ObjectUnLockResponse{}
	mi := &file_proto_actorlocation_inner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectUnLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectUnLockResponse) ProtoMessage() {}

func (x *ObjectUnLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actorlocation_inner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectUnLockResponse.ProtoReflect.Descriptor instead.
func (*ObjectUnLockResponse) Descriptor() ([]byte, []int) {
	return file_proto_actorlocation_inner_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectUnLockResponse) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *ObjectUnLockResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ObjectUnLockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ObjectRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         int32                  `protobuf:"varint,1,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Key           int64                  `protobuf:"varint,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRemoveRequest) Reset() {
	*x = ObjectRemoveRequest{}
	mi := &file_proto_actorlocation_inner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRemoveRequest) ProtoMessage() {}

func (x *ObjectRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actorlocation_inner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRemoveRequest.ProtoReflect.Descriptor instead.
func (*ObjectRemoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_actorlocation_inner_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectRemoveRequest) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *ObjectRemoveRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ObjectRemoveRequest) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

type ObjectRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         int32                  `protobuf:"varint,1,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectRemoveResponse) Reset() {
	*x = ObjectRemoveResponse{}
	mi := &file_proto_actorlocation_inner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRemoveResponse) ProtoMessage() {}

func (x *ObjectRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actorlocation_inner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRemoveResponse.ProtoReflect.Descriptor instead.
func (*ObjectRemoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_actorlocation_inner_proto_rawDescGZIP(), []int{8}
}

func (x *ObjectRemoveResponse) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *ObjectRemoveResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ObjectRemoveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ObjectGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         int32                  `protobuf:"varint,1,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Key           int64                  `protobuf:"varint,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectGetRequest) Reset() {
	*x = ObjectGetRequest{}
	mi := &file_proto_actorlocation_inner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectGetRequest) ProtoMessage() {}

func (x *ObjectGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actorlocation_inner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectGetRequest.ProtoReflect.Descriptor instead.
func (*ObjectGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_actorlocation_inner_proto_rawDescGZIP(), []int{9}
}

func (x *ObjectGetRequest) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *ObjectGetRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ObjectGetRequest) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

type ObjectGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         int32                  `protobuf:"varint,1,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ActorId       *ActorId               `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectGetResponse) Reset() {
	*x = ObjectGetResponse{}
	mi := &file_proto_actorlocation_inner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectGetResponse) ProtoMessage() {}

func (x *ObjectGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actorlocation_inner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectGetResponse.ProtoReflect.Descriptor instead.
func (*ObjectGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_actorlocation_inner_proto_rawDescGZIP(), []int{10}
}

func (x *ObjectGetResponse) GetRpcId() int32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *ObjectGetResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ObjectGetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ObjectGetResponse) GetActorId() *ActorId {
	if x != nil {
		return x.ActorId
	}
	return nil
}

var File_proto_actorlocation_inner_proto protoreflect.FileDescriptor

const file_proto_actorlocation_inner_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/actorlocation_inner.proto\x12\x18etgo.proto.actorlocation\"d\n" +
	"\aActorId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\x05R\tprocessId\x12\x19\n" +
	"\bfiber_id\x18\x02 \x01(\x03R\afiberId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\x03R\n" +
	"instanceId\"\x8d\x01\n" +
	"\x10ObjectAddRequest\x12\x15\n" +
	"\x06rpc_id\x18\x01 \x01(\x05R\x05rpcId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x10\n" +
	"\x03key\x18\x03 \x01(\x03R\x03key\x12<\n" +
	"\bactor_id\x18\x04 \x01(\v2!.etgo.proto.actorlocation.ActorIdR\aactorId\"Z\n" +
	"\x11ObjectAddResponse\x12\x15\n" +
	"\x06rpc_id\x18\x01 \x01(\x05R\x05rpcId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\x05R\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa2\x01\n" +
	"\x11ObjectLockRequest\x12\x15\n" +
	"\x06rpc_id\x18\x01 \x01(\x05R\x05rpcId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x10\n" +
	"\x03key\x18\x03 \x01(\x03R\x03key\x12<\n" +
	"\bactor_id\x18\x04 \x01(\v2!.etgo.proto.actorlocation.ActorIdR\aactorId\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x05R\x04time\"[\n" +
	"\x12ObjectLockResponse\x12\x15\n" +
	"\x06rpc_id\x18\x01 \x01(\x05R\x05rpcId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\x05R\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xdc\x01\n" +
	"\x13ObjectUnLockRequest\x12\x15\n" +
	"\x06rpc_id\x18\x01 \x01(\x05R\x05rpcId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x10\n" +
	"\x03key\x18\x03 \x01(\x03R\x03key\x12C\n" +
	"\fold_actor_id\x18\x04 \x01(\v2!.etgo.proto.actorlocation.ActorIdR\n" +
	"oldActorId\x12C\n" +
	"\fnew_actor_id\x18\x05 \x01(\v2!.etgo.proto.actorlocation.ActorIdR\n" +
	"newActorId\"]\n" +
	"\x14ObjectUnLockResponse\x12\x15\n" +
	"\x06rpc_id\x18\x01 \x01(\x05R\x05rpcId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\x05R\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"R\n" +
	"\x13ObjectRemoveRequest\x12\x15\n" +
	"\x06rpc_id\x18\x01 \x01(\x05R\x05rpcId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x10\n" +
	"\x03key\x18\x03 \x01(\x03R\x03key\"]\n" +
	"\x14ObjectRemoveResponse\x12\x15\n" +
	"\x06rpc_id\x18\x01 \x01(\x05R\x05rpcId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\x05R\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"O\n" +
	"\x10ObjectGetRequest\x12\x15\n" +
	"\x06rpc_id\x18\x01 \x01(\x05R\x05rpcId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x10\n" +
	"\x03key\x18\x03 \x01(\x03R\x03key\"\x98\x01\n" +
	"\x11ObjectGetResponse\x12\x15\n" +
	"\x06rpc_id\x18\x01 \x01(\x05R\x05rpcId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\x05R\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12<\n" +
	"\bactor_id\x18\x05 \x01(\v2!.etgo.proto.actorlocation.ActorIdR\aactorIdB.Z,github.com/jerbe/et-go/proto/actorlocationpbb\x06proto3"

var (
	file_proto_actorlocation_inner_proto_rawDescOnce sync.Once
	file_proto_actorlocation_inner_proto_rawDescData []byte
)

func file_proto_actorlocation_inner_proto_rawDescGZIP() []byte {
	file_proto_actorlocation_inner_proto_rawDescOnce.Do(func() {
		file_proto_actorlocation_inner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_actorlocation_inner_proto_rawDesc), len(file_proto_actorlocation_inner_proto_rawDesc)))
	})
	return file_proto_actorlocation_inner_proto_rawDescData
}

var file_proto_actorlocation_inner_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_actorlocation_inner_proto_goTypes = []any{
	(*ActorId)(nil),              // 0: etgo.proto.actorlocation.ActorId
	(*ObjectAddRequest)(nil),     // 1: etgo.proto.actorlocation.ObjectAddRequest
	(*ObjectAddResponse)(nil),    // 2: etgo.proto.actorlocation.ObjectAddResponse
	(*ObjectLockRequest)(nil),    // 3: etgo.proto.actorlocation.ObjectLockRequest
	(*ObjectLockResponse)(nil),   // 4: etgo.proto.actorlocation.ObjectLockResponse
	(*ObjectUnLockRequest)(nil),  // 5: etgo.proto.actorlocation.ObjectUnLockRequest
	(*ObjectUnLockResponse)(nil), // 6: etgo.proto.actorlocation.ObjectUnLockResponse
	(*ObjectRemoveRequest)(nil),  // 7: etgo.proto.actorlocation.ObjectRemoveRequest
	(*ObjectRemoveResponse)(nil), // 8: etgo.proto.actorlocation.ObjectRemoveResponse
	(*ObjectGetRequest)(nil),     // 9: etgo.proto.actorlocation.ObjectGetRequest
	(*ObjectGetResponse)(nil),    // 10: etgo.proto.actorlocation.ObjectGetResponse
}
var file_proto_actorlocation_inner_proto_depIdxs = []int32{
	0, // 0: etgo.proto.actorlocation.ObjectAddRequest.actor_id:type_name -> etgo.proto.actorlocation.ActorId
	0, // 1: etgo.proto.actorlocation.ObjectLockRequest.actor_id:type_name -> etgo.proto.actorlocation.ActorId
	0, // 2: etgo.proto.actorlocation.ObjectUnLockRequest.old_actor_id:type_name -> etgo.proto.actorlocation.ActorId
	0, // 3: etgo.proto.actorlocation.ObjectUnLockRequest.new_actor_id:type_name -> etgo.proto.actorlocation.ActorId
	0, // 4: etgo.proto.actorlocation.ObjectGetResponse.actor_id:type_name -> etgo.proto.actorlocation.ActorId
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_actorlocation_inner_proto_init() }
func file_proto_actorlocation_inner_proto_init() {
	if File_proto_actorlocation_inner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_actorlocation_inner_proto_rawDesc), len(file_proto_actorlocation_inner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_actorlocation_inner_proto_goTypes,
		DependencyIndexes: file_proto_actorlocation_inner_proto_depIdxs,
		MessageInfos:      file_proto_actorlocation_inner_proto_msgTypes,
	}.Build()
	File_proto_actorlocation_inner_proto = out.File
	file_proto_actorlocation_inner_proto_goTypes = nil
	file_proto_actorlocation_inner_proto_depIdxs = nil
}
