// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/central_inner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type R2Central_AccountLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *R2Central_AccountLogin) Reset() {
	*x = R2Central_AccountLogin{}
	mi := &file_proto_central_inner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *R2Central_AccountLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*R2Central_AccountLogin) ProtoMessage() {}

func (x *R2Central_AccountLogin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_central_inner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use R2Central_AccountLogin.ProtoReflect.Descriptor instead.
func (*R2Central_AccountLogin) Descriptor() ([]byte, []int) {
	return file_proto_central_inner_proto_rawDescGZIP(), []int{0}
}

func (x *R2Central_AccountLogin) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *R2Central_AccountLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *R2Central_AccountLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Central2R_AccountLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	AccessToken   string                 `protobuf:"bytes,4,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Central2R_AccountLogin) Reset() {
	*x = Central2R_AccountLogin{}
	mi := &file_proto_central_inner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Central2R_AccountLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Central2R_AccountLogin) ProtoMessage() {}

func (x *Central2R_AccountLogin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_central_inner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Central2R_AccountLogin.ProtoReflect.Descriptor instead.
func (*Central2R_AccountLogin) Descriptor() ([]byte, []int) {
	return file_proto_central_inner_proto_rawDescGZIP(), []int{1}
}

func (x *Central2R_AccountLogin) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *Central2R_AccountLogin) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *Central2R_AccountLogin) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Central2R_AccountLogin) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

var File_proto_central_inner_proto protoreflect.FileDescriptor

const file_proto_central_inner_proto_rawDesc = "" +
	"\n" +
	"\x19proto/central_inner.proto\x12\x05proto\"f\n" +
	"\x16R2Central_AccountLogin\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\"\x80\x01\n" +
	"\x16Central2R_AccountLogin\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\x12 \n" +
	"\vAccessToken\x18\x04 \x01(\tR\vAccessTokenB\x1eZ\x1cgithub.com/jerbe/et-go/protob\x06proto3"

var (
	file_proto_central_inner_proto_rawDescOnce sync.Once
	file_proto_central_inner_proto_rawDescData []byte
)

func file_proto_central_inner_proto_rawDescGZIP() []byte {
	file_proto_central_inner_proto_rawDescOnce.Do(func() {
		file_proto_central_inner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_central_inner_proto_rawDesc), len(file_proto_central_inner_proto_rawDesc)))
	})
	return file_proto_central_inner_proto_rawDescData
}

var file_proto_central_inner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_central_inner_proto_goTypes = []any{
	(*R2Central_AccountLogin)(nil), // 0: proto.R2Central_AccountLogin
	(*Central2R_AccountLogin)(nil), // 1: proto.Central2R_AccountLogin
}
var file_proto_central_inner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_central_inner_proto_init() }
func file_proto_central_inner_proto_init() {
	if File_proto_central_inner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_central_inner_proto_rawDesc), len(file_proto_central_inner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_central_inner_proto_goTypes,
		DependencyIndexes: file_proto_central_inner_proto_depIdxs,
		MessageInfos:      file_proto_central_inner_proto_msgTypes,
	}.Build()
	File_proto_central_inner_proto = out.File
	file_proto_central_inner_proto_goTypes = nil
	file_proto_central_inner_proto_depIdxs = nil
}
