// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/launch_inner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type G2Game_Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *G2Game_Login) Reset() {
	*x = G2Game_Login{}
	mi := &file_proto_launch_inner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *G2Game_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2Game_Login) ProtoMessage() {}

func (x *G2Game_Login) ProtoReflect() protoreflect.Message {
	mi := &file_proto_launch_inner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2Game_Login.ProtoReflect.Descriptor instead.
func (*G2Game_Login) Descriptor() ([]byte, []int) {
	return file_proto_launch_inner_proto_rawDescGZIP(), []int{0}
}

func (x *G2Game_Login) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *G2Game_Login) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type Game2G_Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	AccountId     int64                  `protobuf:"varint,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ZoneId        int32                  `protobuf:"varint,5,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	PlayerId      int64                  `protobuf:"varint,6,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game2G_Login) Reset() {
	*x = Game2G_Login{}
	mi := &file_proto_launch_inner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game2G_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game2G_Login) ProtoMessage() {}

func (x *Game2G_Login) ProtoReflect() protoreflect.Message {
	mi := &file_proto_launch_inner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game2G_Login.ProtoReflect.Descriptor instead.
func (*Game2G_Login) Descriptor() ([]byte, []int) {
	return file_proto_launch_inner_proto_rawDescGZIP(), []int{1}
}

func (x *Game2G_Login) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *Game2G_Login) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *Game2G_Login) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Game2G_Login) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Game2G_Login) GetZoneId() int32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *Game2G_Login) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_proto_launch_inner_proto protoreflect.FileDescriptor

const file_proto_launch_inner_proto_rawDesc = "" +
	"\n" +
	"\x18proto/launch_inner.proto\x12\n" +
	"etgo.proto\"D\n" +
	"\fG2Game_Login\x12\x15\n" +
	"\x06rpc_id\x18\x01 \x01(\rR\x05rpcId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\"\xaa\x01\n" +
	"\fGame2G_Login\x12\x15\n" +
	"\x06rpc_id\x18\x01 \x01(\rR\x05rpcId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\x05R\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\x03R\taccountId\x12\x17\n" +
	"\azone_id\x18\x05 \x01(\x05R\x06zoneId\x12\x1b\n" +
	"\tplayer_id\x18\x06 \x01(\x03R\bplayerIdB\x1eZ\x1cgithub.com/jerbe/et-go/protob\x06proto3"

var (
	file_proto_launch_inner_proto_rawDescOnce sync.Once
	file_proto_launch_inner_proto_rawDescData []byte
)

func file_proto_launch_inner_proto_rawDescGZIP() []byte {
	file_proto_launch_inner_proto_rawDescOnce.Do(func() {
		file_proto_launch_inner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_launch_inner_proto_rawDesc), len(file_proto_launch_inner_proto_rawDesc)))
	})
	return file_proto_launch_inner_proto_rawDescData
}

var file_proto_launch_inner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_launch_inner_proto_goTypes = []any{
	(*G2Game_Login)(nil), // 0: etgo.proto.G2Game_Login
	(*Game2G_Login)(nil), // 1: etgo.proto.Game2G_Login
}
var file_proto_launch_inner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_launch_inner_proto_init() }
func file_proto_launch_inner_proto_init() {
	if File_proto_launch_inner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_launch_inner_proto_rawDesc), len(file_proto_launch_inner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_launch_inner_proto_goTypes,
		DependencyIndexes: file_proto_launch_inner_proto_depIdxs,
		MessageInfos:      file_proto_launch_inner_proto_msgTypes,
	}.Build()
	File_proto_launch_inner_proto = out.File
	file_proto_launch_inner_proto_goTypes = nil
	file_proto_launch_inner_proto_depIdxs = nil
}
