// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/login_inner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type R2G_GateAssign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *R2G_GateAssign) Reset() {
	*x = R2G_GateAssign{}
	mi := &file_proto_login_inner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *R2G_GateAssign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*R2G_GateAssign) ProtoMessage() {}

func (x *R2G_GateAssign) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_inner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use R2G_GateAssign.ProtoReflect.Descriptor instead.
func (*R2G_GateAssign) Descriptor() ([]byte, []int) {
	return file_proto_login_inner_proto_rawDescGZIP(), []int{0}
}

func (x *R2G_GateAssign) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *R2G_GateAssign) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type G2R_GateAssign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	GateId        int64                  `protobuf:"varint,4,opt,name=GateId,proto3" json:"GateId,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *G2R_GateAssign) Reset() {
	*x = G2R_GateAssign{}
	mi := &file_proto_login_inner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *G2R_GateAssign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2R_GateAssign) ProtoMessage() {}

func (x *G2R_GateAssign) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_inner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2R_GateAssign.ProtoReflect.Descriptor instead.
func (*G2R_GateAssign) Descriptor() ([]byte, []int) {
	return file_proto_login_inner_proto_rawDescGZIP(), []int{1}
}

func (x *G2R_GateAssign) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *G2R_GateAssign) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *G2R_GateAssign) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *G2R_GateAssign) GetGateId() int64 {
	if x != nil {
		return x.GateId
	}
	return 0
}

func (x *G2R_GateAssign) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type G2M_SessionDisconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *G2M_SessionDisconnect) Reset() {
	*x = G2M_SessionDisconnect{}
	mi := &file_proto_login_inner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *G2M_SessionDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2M_SessionDisconnect) ProtoMessage() {}

func (x *G2M_SessionDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_inner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2M_SessionDisconnect.ProtoReflect.Descriptor instead.
func (*G2M_SessionDisconnect) Descriptor() ([]byte, []int) {
	return file_proto_login_inner_proto_rawDescGZIP(), []int{2}
}

func (x *G2M_SessionDisconnect) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

var File_proto_login_inner_proto protoreflect.FileDescriptor

const file_proto_login_inner_proto_rawDesc = "" +
	"\n" +
	"\x17proto/login_inner.proto\x12\x05proto\"D\n" +
	"\x0eR2G_GateAssign\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1c\n" +
	"\tAccountId\x18\x02 \x01(\x03R\tAccountId\"\x84\x01\n" +
	"\x0eG2R_GateAssign\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\x12\x16\n" +
	"\x06GateId\x18\x04 \x01(\x03R\x06GateId\x12\x14\n" +
	"\x05Token\x18\x05 \x01(\tR\x05Token\"-\n" +
	"\x15G2M_SessionDisconnect\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcIdB\x1eZ\x1cgithub.com/jerbe/et-go/protob\x06proto3"

var (
	file_proto_login_inner_proto_rawDescOnce sync.Once
	file_proto_login_inner_proto_rawDescData []byte
)

func file_proto_login_inner_proto_rawDescGZIP() []byte {
	file_proto_login_inner_proto_rawDescOnce.Do(func() {
		file_proto_login_inner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_login_inner_proto_rawDesc), len(file_proto_login_inner_proto_rawDesc)))
	})
	return file_proto_login_inner_proto_rawDescData
}

var file_proto_login_inner_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_login_inner_proto_goTypes = []any{
	(*R2G_GateAssign)(nil),        // 0: proto.R2G_GateAssign
	(*G2R_GateAssign)(nil),        // 1: proto.G2R_GateAssign
	(*G2M_SessionDisconnect)(nil), // 2: proto.G2M_SessionDisconnect
}
var file_proto_login_inner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_login_inner_proto_init() }
func file_proto_login_inner_proto_init() {
	if File_proto_login_inner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_login_inner_proto_rawDesc), len(file_proto_login_inner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_login_inner_proto_goTypes,
		DependencyIndexes: file_proto_login_inner_proto_depIdxs,
		MessageInfos:      file_proto_login_inner_proto_msgTypes,
	}.Build()
	File_proto_login_inner_proto = out.File
	file_proto_login_inner_proto_goTypes = nil
	file_proto_login_inner_proto_depIdxs = nil
}
