// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/login_outer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2R_Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	ZoneId        int32                  `protobuf:"varint,3,opt,name=ZoneId,proto3" json:"ZoneId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2R_Login) Reset() {
	*x = C2R_Login{}
	mi := &file_proto_login_outer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2R_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2R_Login) ProtoMessage() {}

func (x *C2R_Login) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_outer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2R_Login.ProtoReflect.Descriptor instead.
func (*C2R_Login) Descriptor() ([]byte, []int) {
	return file_proto_login_outer_proto_rawDescGZIP(), []int{0}
}

func (x *C2R_Login) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *C2R_Login) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *C2R_Login) GetZoneId() int32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

type R2C_Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	GateId        int64                  `protobuf:"varint,5,opt,name=GateId,proto3" json:"GateId,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *R2C_Login) Reset() {
	*x = R2C_Login{}
	mi := &file_proto_login_outer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *R2C_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*R2C_Login) ProtoMessage() {}

func (x *R2C_Login) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_outer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use R2C_Login.ProtoReflect.Descriptor instead.
func (*R2C_Login) Descriptor() ([]byte, []int) {
	return file_proto_login_outer_proto_rawDescGZIP(), []int{1}
}

func (x *R2C_Login) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *R2C_Login) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *R2C_Login) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *R2C_Login) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *R2C_Login) GetGateId() int64 {
	if x != nil {
		return x.GateId
	}
	return 0
}

func (x *R2C_Login) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type C2G_LoginGate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	GateId        int64                  `protobuf:"varint,3,opt,name=GateId,proto3" json:"GateId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2G_LoginGate) Reset() {
	*x = C2G_LoginGate{}
	mi := &file_proto_login_outer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2G_LoginGate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2G_LoginGate) ProtoMessage() {}

func (x *C2G_LoginGate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_outer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2G_LoginGate.ProtoReflect.Descriptor instead.
func (*C2G_LoginGate) Descriptor() ([]byte, []int) {
	return file_proto_login_outer_proto_rawDescGZIP(), []int{2}
}

func (x *C2G_LoginGate) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *C2G_LoginGate) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *C2G_LoginGate) GetGateId() int64 {
	if x != nil {
		return x.GateId
	}
	return 0
}

type G2C_LoginGate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RpcId          uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error          int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	PlayerId       int64                  `protobuf:"varint,4,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	CharacterCount int64                  `protobuf:"varint,5,opt,name=CharacterCount,proto3" json:"CharacterCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *G2C_LoginGate) Reset() {
	*x = G2C_LoginGate{}
	mi := &file_proto_login_outer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *G2C_LoginGate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2C_LoginGate) ProtoMessage() {}

func (x *G2C_LoginGate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_outer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2C_LoginGate.ProtoReflect.Descriptor instead.
func (*G2C_LoginGate) Descriptor() ([]byte, []int) {
	return file_proto_login_outer_proto_rawDescGZIP(), []int{3}
}

func (x *G2C_LoginGate) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *G2C_LoginGate) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *G2C_LoginGate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *G2C_LoginGate) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *G2C_LoginGate) GetCharacterCount() int64 {
	if x != nil {
		return x.CharacterCount
	}
	return 0
}

type C2G_Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2G_Ping) Reset() {
	*x = C2G_Ping{}
	mi := &file_proto_login_outer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2G_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2G_Ping) ProtoMessage() {}

func (x *C2G_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_outer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2G_Ping.ProtoReflect.Descriptor instead.
func (*C2G_Ping) Descriptor() ([]byte, []int) {
	return file_proto_login_outer_proto_rawDescGZIP(), []int{4}
}

func (x *C2G_Ping) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

type G2C_Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Time          int64                  `protobuf:"varint,4,opt,name=Time,proto3" json:"Time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *G2C_Ping) Reset() {
	*x = G2C_Ping{}
	mi := &file_proto_login_outer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *G2C_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2C_Ping) ProtoMessage() {}

func (x *G2C_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_login_outer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2C_Ping.ProtoReflect.Descriptor instead.
func (*G2C_Ping) Descriptor() ([]byte, []int) {
	return file_proto_login_outer_proto_rawDescGZIP(), []int{5}
}

func (x *G2C_Ping) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *G2C_Ping) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *G2C_Ping) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *G2C_Ping) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_proto_login_outer_proto protoreflect.FileDescriptor

const file_proto_login_outer_proto_rawDesc = "" +
	"\n" +
	"\x17proto/login_outer.proto\x12\x05proto\"[\n" +
	"\tC2R_Login\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12 \n" +
	"\vAccessToken\x18\x02 \x01(\tR\vAccessToken\x12\x16\n" +
	"\x06ZoneId\x18\x03 \x01(\x05R\x06ZoneId\"\x99\x01\n" +
	"\tR2C_Login\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\x12\x18\n" +
	"\aAddress\x18\x04 \x01(\tR\aAddress\x12\x16\n" +
	"\x06GateId\x18\x05 \x01(\x03R\x06GateId\x12\x14\n" +
	"\x05Token\x18\x06 \x01(\tR\x05Token\"S\n" +
	"\rC2G_LoginGate\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Token\x18\x02 \x01(\tR\x05Token\x12\x16\n" +
	"\x06GateId\x18\x03 \x01(\x03R\x06GateId\"\x99\x01\n" +
	"\rG2C_LoginGate\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\x12\x1a\n" +
	"\bPlayerId\x18\x04 \x01(\x03R\bPlayerId\x12&\n" +
	"\x0eCharacterCount\x18\x05 \x01(\x03R\x0eCharacterCount\" \n" +
	"\bC2G_Ping\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\"d\n" +
	"\bG2C_Ping\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Time\x18\x04 \x01(\x03R\x04TimeB\x1eZ\x1cgithub.com/jerbe/et-go/protob\x06proto3"

var (
	file_proto_login_outer_proto_rawDescOnce sync.Once
	file_proto_login_outer_proto_rawDescData []byte
)

func file_proto_login_outer_proto_rawDescGZIP() []byte {
	file_proto_login_outer_proto_rawDescOnce.Do(func() {
		file_proto_login_outer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_login_outer_proto_rawDesc), len(file_proto_login_outer_proto_rawDesc)))
	})
	return file_proto_login_outer_proto_rawDescData
}

var file_proto_login_outer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_login_outer_proto_goTypes = []any{
	(*C2R_Login)(nil),     // 0: proto.C2R_Login
	(*R2C_Login)(nil),     // 1: proto.R2C_Login
	(*C2G_LoginGate)(nil), // 2: proto.C2G_LoginGate
	(*G2C_LoginGate)(nil), // 3: proto.G2C_LoginGate
	(*C2G_Ping)(nil),      // 4: proto.C2G_Ping
	(*G2C_Ping)(nil),      // 5: proto.G2C_Ping
}
var file_proto_login_outer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_login_outer_proto_init() }
func file_proto_login_outer_proto_init() {
	if File_proto_login_outer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_login_outer_proto_rawDesc), len(file_proto_login_outer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_login_outer_proto_goTypes,
		DependencyIndexes: file_proto_login_outer_proto_depIdxs,
		MessageInfos:      file_proto_login_outer_proto_msgTypes,
	}.Build()
	File_proto_login_outer_proto = out.File
	file_proto_login_outer_proto_goTypes = nil
	file_proto_login_outer_proto_depIdxs = nil
}
