// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/lockstep_outer.proto

package locksteppb

import (
	mapouterpb "github.com/jerbe/et-go/proto/mapouterpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TSVector2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int64                  `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y             int64                  `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TSVector2) Reset() {
	*x = TSVector2{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TSVector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TSVector2) ProtoMessage() {}

func (x *TSVector2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TSVector2.ProtoReflect.Descriptor instead.
func (*TSVector2) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{0}
}

func (x *TSVector2) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TSVector2) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type LSInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             *TSVector2             `protobuf:"bytes,1,opt,name=V,proto3" json:"V,omitempty"`
	Button        int32                  `protobuf:"varint,2,opt,name=Button,proto3" json:"Button,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSInput) Reset() {
	*x = LSInput{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSInput) ProtoMessage() {}

func (x *LSInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSInput.ProtoReflect.Descriptor instead.
func (*LSInput) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{1}
}

func (x *LSInput) GetV() *TSVector2 {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *LSInput) GetButton() int32 {
	if x != nil {
		return x.Button
	}
	return 0
}

type OneFrameInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inputs        map[int64]*LSInput     `protobuf:"bytes,1,rep,name=Inputs,proto3" json:"Inputs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneFrameInputs) Reset() {
	*x = OneFrameInputs{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneFrameInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneFrameInputs) ProtoMessage() {}

func (x *OneFrameInputs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneFrameInputs.ProtoReflect.Descriptor instead.
func (*OneFrameInputs) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{2}
}

func (x *OneFrameInputs) GetInputs() map[int64]*LSInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type LockStepUnitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Position      *mapouterpb.Float3     `protobuf:"bytes,2,opt,name=Position,proto3" json:"Position,omitempty"`
	Rotation      *mapouterpb.Quaternion `protobuf:"bytes,3,opt,name=Rotation,proto3" json:"Rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockStepUnitInfo) Reset() {
	*x = LockStepUnitInfo{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockStepUnitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockStepUnitInfo) ProtoMessage() {}

func (x *LockStepUnitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockStepUnitInfo.ProtoReflect.Descriptor instead.
func (*LockStepUnitInfo) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{3}
}

func (x *LockStepUnitInfo) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *LockStepUnitInfo) GetPosition() *mapouterpb.Float3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *LockStepUnitInfo) GetRotation() *mapouterpb.Quaternion {
	if x != nil {
		return x.Rotation
	}
	return nil
}

type C2G_Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2G_Match) Reset() {
	*x = C2G_Match{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2G_Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2G_Match) ProtoMessage() {}

func (x *C2G_Match) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2G_Match.ProtoReflect.Descriptor instead.
func (*C2G_Match) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{4}
}

func (x *C2G_Match) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *C2G_Match) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type G2C_Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *G2C_Match) Reset() {
	*x = G2C_Match{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *G2C_Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2C_Match) ProtoMessage() {}

func (x *G2C_Match) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2C_Match.ProtoReflect.Descriptor instead.
func (*G2C_Match) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{5}
}

func (x *G2C_Match) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *G2C_Match) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *G2C_Match) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type G2C_NotifyMatchSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapActorId    int64                  `protobuf:"varint,1,opt,name=MapActorId,proto3" json:"MapActorId,omitempty"`
	RoomActorId   int64                  `protobuf:"varint,2,opt,name=RoomActorId,proto3" json:"RoomActorId,omitempty"`
	MapActor      *ActorId               `protobuf:"bytes,3,opt,name=MapActor,proto3" json:"MapActor,omitempty"`
	RoomActor     *ActorId               `protobuf:"bytes,4,opt,name=RoomActor,proto3" json:"RoomActor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *G2C_NotifyMatchSuccess) Reset() {
	*x = G2C_NotifyMatchSuccess{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *G2C_NotifyMatchSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2C_NotifyMatchSuccess) ProtoMessage() {}

func (x *G2C_NotifyMatchSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2C_NotifyMatchSuccess.ProtoReflect.Descriptor instead.
func (*G2C_NotifyMatchSuccess) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{6}
}

func (x *G2C_NotifyMatchSuccess) GetMapActorId() int64 {
	if x != nil {
		return x.MapActorId
	}
	return 0
}

func (x *G2C_NotifyMatchSuccess) GetRoomActorId() int64 {
	if x != nil {
		return x.RoomActorId
	}
	return 0
}

func (x *G2C_NotifyMatchSuccess) GetMapActor() *ActorId {
	if x != nil {
		return x.MapActor
	}
	return nil
}

func (x *G2C_NotifyMatchSuccess) GetRoomActor() *ActorId {
	if x != nil {
		return x.RoomActor
	}
	return nil
}

type C2Room_ChangeSceneFinish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2Room_ChangeSceneFinish) Reset() {
	*x = C2Room_ChangeSceneFinish{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2Room_ChangeSceneFinish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2Room_ChangeSceneFinish) ProtoMessage() {}

func (x *C2Room_ChangeSceneFinish) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2Room_ChangeSceneFinish.ProtoReflect.Descriptor instead.
func (*C2Room_ChangeSceneFinish) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{7}
}

func (x *C2Room_ChangeSceneFinish) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *C2Room_ChangeSceneFinish) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type Room2C_Start struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	UnitInfos     []*LockStepUnitInfo    `protobuf:"bytes,3,rep,name=UnitInfos,proto3" json:"UnitInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room2C_Start) Reset() {
	*x = Room2C_Start{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room2C_Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room2C_Start) ProtoMessage() {}

func (x *Room2C_Start) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room2C_Start.ProtoReflect.Descriptor instead.
func (*Room2C_Start) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{8}
}

func (x *Room2C_Start) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *Room2C_Start) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Room2C_Start) GetUnitInfos() []*LockStepUnitInfo {
	if x != nil {
		return x.UnitInfos
	}
	return nil
}

type FrameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Frame         int32                  `protobuf:"varint,3,opt,name=Frame,proto3" json:"Frame,omitempty"`
	Input         *LSInput               `protobuf:"bytes,4,opt,name=Input,proto3" json:"Input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameMessage) Reset() {
	*x = FrameMessage{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameMessage) ProtoMessage() {}

func (x *FrameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameMessage.ProtoReflect.Descriptor instead.
func (*FrameMessage) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{9}
}

func (x *FrameMessage) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *FrameMessage) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *FrameMessage) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *FrameMessage) GetInput() *LSInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type FrameMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=Accepted,proto3" json:"Accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameMessageResponse) Reset() {
	*x = FrameMessageResponse{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameMessageResponse) ProtoMessage() {}

func (x *FrameMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameMessageResponse.ProtoReflect.Descriptor instead.
func (*FrameMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{10}
}

func (x *FrameMessageResponse) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *FrameMessageResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type C2Room_CheckHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Frame         int32                  `protobuf:"varint,3,opt,name=Frame,proto3" json:"Frame,omitempty"`
	Hash          int64                  `protobuf:"varint,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2Room_CheckHash) Reset() {
	*x = C2Room_CheckHash{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2Room_CheckHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2Room_CheckHash) ProtoMessage() {}

func (x *C2Room_CheckHash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2Room_CheckHash.ProtoReflect.Descriptor instead.
func (*C2Room_CheckHash) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{11}
}

func (x *C2Room_CheckHash) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *C2Room_CheckHash) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *C2Room_CheckHash) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *C2Room_CheckHash) GetHash() int64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

type CheckHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Frame         int32                  `protobuf:"varint,2,opt,name=Frame,proto3" json:"Frame,omitempty"`
	SnapshotFrame int32                  `protobuf:"varint,3,opt,name=SnapshotFrame,proto3" json:"SnapshotFrame,omitempty"`
	Snapshot      []byte                 `protobuf:"bytes,4,opt,name=Snapshot,proto3" json:"Snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHashResponse) Reset() {
	*x = CheckHashResponse{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHashResponse) ProtoMessage() {}

func (x *CheckHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHashResponse.ProtoReflect.Descriptor instead.
func (*CheckHashResponse) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{12}
}

func (x *CheckHashResponse) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *CheckHashResponse) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *CheckHashResponse) GetSnapshotFrame() int32 {
	if x != nil {
		return x.SnapshotFrame
	}
	return 0
}

func (x *CheckHashResponse) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type Room2C_CheckHashFail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Frame         int32                  `protobuf:"varint,2,opt,name=Frame,proto3" json:"Frame,omitempty"`
	SnapshotFrame int32                  `protobuf:"varint,3,opt,name=SnapshotFrame,proto3" json:"SnapshotFrame,omitempty"`
	Snapshot      []byte                 `protobuf:"bytes,4,opt,name=Snapshot,proto3" json:"Snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room2C_CheckHashFail) Reset() {
	*x = Room2C_CheckHashFail{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room2C_CheckHashFail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room2C_CheckHashFail) ProtoMessage() {}

func (x *Room2C_CheckHashFail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room2C_CheckHashFail.ProtoReflect.Descriptor instead.
func (*Room2C_CheckHashFail) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{13}
}

func (x *Room2C_CheckHashFail) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *Room2C_CheckHashFail) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *Room2C_CheckHashFail) GetSnapshotFrame() int32 {
	if x != nil {
		return x.SnapshotFrame
	}
	return 0
}

func (x *Room2C_CheckHashFail) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type Room2C_AdjustUpdateTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	DiffTime      int64                  `protobuf:"varint,2,opt,name=DiffTime,proto3" json:"DiffTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room2C_AdjustUpdateTime) Reset() {
	*x = Room2C_AdjustUpdateTime{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room2C_AdjustUpdateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room2C_AdjustUpdateTime) ProtoMessage() {}

func (x *Room2C_AdjustUpdateTime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room2C_AdjustUpdateTime.ProtoReflect.Descriptor instead.
func (*Room2C_AdjustUpdateTime) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{14}
}

func (x *Room2C_AdjustUpdateTime) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *Room2C_AdjustUpdateTime) GetDiffTime() int64 {
	if x != nil {
		return x.DiffTime
	}
	return 0
}

type Room2C_Reconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	UnitInfos     []*LockStepUnitInfo    `protobuf:"bytes,3,rep,name=UnitInfos,proto3" json:"UnitInfos,omitempty"`
	Frame         int32                  `protobuf:"varint,4,opt,name=Frame,proto3" json:"Frame,omitempty"`
	SnapshotFrame int32                  `protobuf:"varint,5,opt,name=SnapshotFrame,proto3" json:"SnapshotFrame,omitempty"`
	Snapshot      []byte                 `protobuf:"bytes,6,opt,name=Snapshot,proto3" json:"Snapshot,omitempty"`
	FrameInputs   []*OneFrameInputs      `protobuf:"bytes,7,rep,name=FrameInputs,proto3" json:"FrameInputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room2C_Reconnect) Reset() {
	*x = Room2C_Reconnect{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room2C_Reconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room2C_Reconnect) ProtoMessage() {}

func (x *Room2C_Reconnect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room2C_Reconnect.ProtoReflect.Descriptor instead.
func (*Room2C_Reconnect) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{15}
}

func (x *Room2C_Reconnect) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *Room2C_Reconnect) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Room2C_Reconnect) GetUnitInfos() []*LockStepUnitInfo {
	if x != nil {
		return x.UnitInfos
	}
	return nil
}

func (x *Room2C_Reconnect) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *Room2C_Reconnect) GetSnapshotFrame() int32 {
	if x != nil {
		return x.SnapshotFrame
	}
	return 0
}

func (x *Room2C_Reconnect) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *Room2C_Reconnect) GetFrameInputs() []*OneFrameInputs {
	if x != nil {
		return x.FrameInputs
	}
	return nil
}

type Match2Map_GetRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	PlayerIds     []int64                `protobuf:"varint,2,rep,packed,name=PlayerIds,proto3" json:"PlayerIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match2Map_GetRoom) Reset() {
	*x = Match2Map_GetRoom{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match2Map_GetRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match2Map_GetRoom) ProtoMessage() {}

func (x *Match2Map_GetRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match2Map_GetRoom.ProtoReflect.Descriptor instead.
func (*Match2Map_GetRoom) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{16}
}

func (x *Match2Map_GetRoom) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *Match2Map_GetRoom) GetPlayerIds() []int64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

type Map2Match_GetRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	MapActorId    int64                  `protobuf:"varint,2,opt,name=MapActorId,proto3" json:"MapActorId,omitempty"`
	RoomActorId   int64                  `protobuf:"varint,3,opt,name=RoomActorId,proto3" json:"RoomActorId,omitempty"`
	MapActor      *ActorId               `protobuf:"bytes,4,opt,name=MapActor,proto3" json:"MapActor,omitempty"`
	RoomActor     *ActorId               `protobuf:"bytes,5,opt,name=RoomActor,proto3" json:"RoomActor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Map2Match_GetRoom) Reset() {
	*x = Map2Match_GetRoom{}
	mi := &file_proto_lockstep_outer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Map2Match_GetRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map2Match_GetRoom) ProtoMessage() {}

func (x *Map2Match_GetRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_outer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map2Match_GetRoom.ProtoReflect.Descriptor instead.
func (*Map2Match_GetRoom) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_outer_proto_rawDescGZIP(), []int{17}
}

func (x *Map2Match_GetRoom) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *Map2Match_GetRoom) GetMapActorId() int64 {
	if x != nil {
		return x.MapActorId
	}
	return 0
}

func (x *Map2Match_GetRoom) GetRoomActorId() int64 {
	if x != nil {
		return x.RoomActorId
	}
	return 0
}

func (x *Map2Match_GetRoom) GetMapActor() *ActorId {
	if x != nil {
		return x.MapActor
	}
	return nil
}

func (x *Map2Match_GetRoom) GetRoomActor() *ActorId {
	if x != nil {
		return x.RoomActor
	}
	return nil
}

var File_proto_lockstep_outer_proto protoreflect.FileDescriptor

const file_proto_lockstep_outer_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/lockstep_outer.proto\x12\x13etgo.proto.lockstep\x1a\x1aproto/lockstep_inner.proto\x1a\x15proto/map_outer.proto\"'\n" +
	"\tTSVector2\x12\f\n" +
	"\x01X\x18\x01 \x01(\x03R\x01X\x12\f\n" +
	"\x01Y\x18\x02 \x01(\x03R\x01Y\"O\n" +
	"\aLSInput\x12,\n" +
	"\x01V\x18\x01 \x01(\v2\x1e.etgo.proto.lockstep.TSVector2R\x01V\x12\x16\n" +
	"\x06Button\x18\x02 \x01(\x05R\x06Button\"\xb2\x01\n" +
	"\x0eOneFrameInputs\x12G\n" +
	"\x06Inputs\x18\x01 \x03(\v2/.etgo.proto.lockstep.OneFrameInputs.InputsEntryR\x06Inputs\x1aW\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.etgo.proto.lockstep.LSInputR\x05value:\x028\x01\"\x88\x01\n" +
	"\x10LockStepUnitInfo\x12\x1a\n" +
	"\bPlayerId\x18\x01 \x01(\x03R\bPlayerId\x12)\n" +
	"\bPosition\x18\x02 \x01(\v2\r.proto.Float3R\bPosition\x12-\n" +
	"\bRotation\x18\x03 \x01(\v2\x11.proto.QuaternionR\bRotation\"=\n" +
	"\tC2G_Match\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1a\n" +
	"\bPlayerId\x18\x02 \x01(\x03R\bPlayerId\"Q\n" +
	"\tG2C_Match\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\"\xd0\x01\n" +
	"\x16G2C_NotifyMatchSuccess\x12\x1e\n" +
	"\n" +
	"MapActorId\x18\x01 \x01(\x03R\n" +
	"MapActorId\x12 \n" +
	"\vRoomActorId\x18\x02 \x01(\x03R\vRoomActorId\x128\n" +
	"\bMapActor\x18\x03 \x01(\v2\x1c.etgo.proto.lockstep.ActorIdR\bMapActor\x12:\n" +
	"\tRoomActor\x18\x04 \x01(\v2\x1c.etgo.proto.lockstep.ActorIdR\tRoomActor\"L\n" +
	"\x18C2Room_ChangeSceneFinish\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1a\n" +
	"\bPlayerId\x18\x02 \x01(\x03R\bPlayerId\"\x87\x01\n" +
	"\fRoom2C_Start\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1c\n" +
	"\tStartTime\x18\x02 \x01(\x03R\tStartTime\x12C\n" +
	"\tUnitInfos\x18\x03 \x03(\v2%.etgo.proto.lockstep.LockStepUnitInfoR\tUnitInfos\"\x8a\x01\n" +
	"\fFrameMessage\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1a\n" +
	"\bPlayerId\x18\x02 \x01(\x03R\bPlayerId\x12\x14\n" +
	"\x05Frame\x18\x03 \x01(\x05R\x05Frame\x122\n" +
	"\x05Input\x18\x04 \x01(\v2\x1c.etgo.proto.lockstep.LSInputR\x05Input\"H\n" +
	"\x14FrameMessageResponse\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1a\n" +
	"\bAccepted\x18\x02 \x01(\bR\bAccepted\"n\n" +
	"\x10C2Room_CheckHash\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1a\n" +
	"\bPlayerId\x18\x02 \x01(\x03R\bPlayerId\x12\x14\n" +
	"\x05Frame\x18\x03 \x01(\x05R\x05Frame\x12\x12\n" +
	"\x04Hash\x18\x04 \x01(\x03R\x04Hash\"\x81\x01\n" +
	"\x11CheckHashResponse\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Frame\x18\x02 \x01(\x05R\x05Frame\x12$\n" +
	"\rSnapshotFrame\x18\x03 \x01(\x05R\rSnapshotFrame\x12\x1a\n" +
	"\bSnapshot\x18\x04 \x01(\fR\bSnapshot\"\x84\x01\n" +
	"\x14Room2C_CheckHashFail\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Frame\x18\x02 \x01(\x05R\x05Frame\x12$\n" +
	"\rSnapshotFrame\x18\x03 \x01(\x05R\rSnapshotFrame\x12\x1a\n" +
	"\bSnapshot\x18\x04 \x01(\fR\bSnapshot\"K\n" +
	"\x17Room2C_AdjustUpdateTime\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1a\n" +
	"\bDiffTime\x18\x02 \x01(\x03R\bDiffTime\"\xaa\x02\n" +
	"\x10Room2C_Reconnect\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1c\n" +
	"\tStartTime\x18\x02 \x01(\x03R\tStartTime\x12C\n" +
	"\tUnitInfos\x18\x03 \x03(\v2%.etgo.proto.lockstep.LockStepUnitInfoR\tUnitInfos\x12\x14\n" +
	"\x05Frame\x18\x04 \x01(\x05R\x05Frame\x12$\n" +
	"\rSnapshotFrame\x18\x05 \x01(\x05R\rSnapshotFrame\x12\x1a\n" +
	"\bSnapshot\x18\x06 \x01(\fR\bSnapshot\x12E\n" +
	"\vFrameInputs\x18\a \x03(\v2#.etgo.proto.lockstep.OneFrameInputsR\vFrameInputs\"G\n" +
	"\x11Match2Map_GetRoom\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1c\n" +
	"\tPlayerIds\x18\x02 \x03(\x03R\tPlayerIds\"\xe1\x01\n" +
	"\x11Map2Match_GetRoom\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1e\n" +
	"\n" +
	"MapActorId\x18\x02 \x01(\x03R\n" +
	"MapActorId\x12 \n" +
	"\vRoomActorId\x18\x03 \x01(\x03R\vRoomActorId\x128\n" +
	"\bMapActor\x18\x04 \x01(\v2\x1c.etgo.proto.lockstep.ActorIdR\bMapActor\x12:\n" +
	"\tRoomActor\x18\x05 \x01(\v2\x1c.etgo.proto.lockstep.ActorIdR\tRoomActorB4Z2github.com/jerbe/et-go/proto/locksteppb;locksteppbb\x06proto3"

var (
	file_proto_lockstep_outer_proto_rawDescOnce sync.Once
	file_proto_lockstep_outer_proto_rawDescData []byte
)

func file_proto_lockstep_outer_proto_rawDescGZIP() []byte {
	file_proto_lockstep_outer_proto_rawDescOnce.Do(func() {
		file_proto_lockstep_outer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lockstep_outer_proto_rawDesc), len(file_proto_lockstep_outer_proto_rawDesc)))
	})
	return file_proto_lockstep_outer_proto_rawDescData
}

var file_proto_lockstep_outer_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_lockstep_outer_proto_goTypes = []any{
	(*TSVector2)(nil),                // 0: etgo.proto.lockstep.TSVector2
	(*LSInput)(nil),                  // 1: etgo.proto.lockstep.LSInput
	(*OneFrameInputs)(nil),           // 2: etgo.proto.lockstep.OneFrameInputs
	(*LockStepUnitInfo)(nil),         // 3: etgo.proto.lockstep.LockStepUnitInfo
	(*C2G_Match)(nil),                // 4: etgo.proto.lockstep.C2G_Match
	(*G2C_Match)(nil),                // 5: etgo.proto.lockstep.G2C_Match
	(*G2C_NotifyMatchSuccess)(nil),   // 6: etgo.proto.lockstep.G2C_NotifyMatchSuccess
	(*C2Room_ChangeSceneFinish)(nil), // 7: etgo.proto.lockstep.C2Room_ChangeSceneFinish
	(*Room2C_Start)(nil),             // 8: etgo.proto.lockstep.Room2C_Start
	(*FrameMessage)(nil),             // 9: etgo.proto.lockstep.FrameMessage
	(*FrameMessageResponse)(nil),     // 10: etgo.proto.lockstep.FrameMessageResponse
	(*C2Room_CheckHash)(nil),         // 11: etgo.proto.lockstep.C2Room_CheckHash
	(*CheckHashResponse)(nil),        // 12: etgo.proto.lockstep.CheckHashResponse
	(*Room2C_CheckHashFail)(nil),     // 13: etgo.proto.lockstep.Room2C_CheckHashFail
	(*Room2C_AdjustUpdateTime)(nil),  // 14: etgo.proto.lockstep.Room2C_AdjustUpdateTime
	(*Room2C_Reconnect)(nil),         // 15: etgo.proto.lockstep.Room2C_Reconnect
	(*Match2Map_GetRoom)(nil),        // 16: etgo.proto.lockstep.Match2Map_GetRoom
	(*Map2Match_GetRoom)(nil),        // 17: etgo.proto.lockstep.Map2Match_GetRoom
	nil,                              // 18: etgo.proto.lockstep.OneFrameInputs.InputsEntry
	(*mapouterpb.Float3)(nil),        // 19: proto.Float3
	(*mapouterpb.Quaternion)(nil),    // 20: proto.Quaternion
	(*ActorId)(nil),                  // 21: etgo.proto.lockstep.ActorId
}
var file_proto_lockstep_outer_proto_depIdxs = []int32{
	0,  // 0: etgo.proto.lockstep.LSInput.V:type_name -> etgo.proto.lockstep.TSVector2
	18, // 1: etgo.proto.lockstep.OneFrameInputs.Inputs:type_name -> etgo.proto.lockstep.OneFrameInputs.InputsEntry
	19, // 2: etgo.proto.lockstep.LockStepUnitInfo.Position:type_name -> proto.Float3
	20, // 3: etgo.proto.lockstep.LockStepUnitInfo.Rotation:type_name -> proto.Quaternion
	21, // 4: etgo.proto.lockstep.G2C_NotifyMatchSuccess.MapActor:type_name -> etgo.proto.lockstep.ActorId
	21, // 5: etgo.proto.lockstep.G2C_NotifyMatchSuccess.RoomActor:type_name -> etgo.proto.lockstep.ActorId
	3,  // 6: etgo.proto.lockstep.Room2C_Start.UnitInfos:type_name -> etgo.proto.lockstep.LockStepUnitInfo
	1,  // 7: etgo.proto.lockstep.FrameMessage.Input:type_name -> etgo.proto.lockstep.LSInput
	3,  // 8: etgo.proto.lockstep.Room2C_Reconnect.UnitInfos:type_name -> etgo.proto.lockstep.LockStepUnitInfo
	2,  // 9: etgo.proto.lockstep.Room2C_Reconnect.FrameInputs:type_name -> etgo.proto.lockstep.OneFrameInputs
	21, // 10: etgo.proto.lockstep.Map2Match_GetRoom.MapActor:type_name -> etgo.proto.lockstep.ActorId
	21, // 11: etgo.proto.lockstep.Map2Match_GetRoom.RoomActor:type_name -> etgo.proto.lockstep.ActorId
	1,  // 12: etgo.proto.lockstep.OneFrameInputs.InputsEntry.value:type_name -> etgo.proto.lockstep.LSInput
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_lockstep_outer_proto_init() }
func file_proto_lockstep_outer_proto_init() {
	if File_proto_lockstep_outer_proto != nil {
		return
	}
	file_proto_lockstep_inner_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lockstep_outer_proto_rawDesc), len(file_proto_lockstep_outer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_lockstep_outer_proto_goTypes,
		DependencyIndexes: file_proto_lockstep_outer_proto_depIdxs,
		MessageInfos:      file_proto_lockstep_outer_proto_msgTypes,
	}.Build()
	File_proto_lockstep_outer_proto = out.File
	file_proto_lockstep_outer_proto_goTypes = nil
	file_proto_lockstep_outer_proto_depIdxs = nil
}
