// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/lockstep_inner.proto

package locksteppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     int32                  `protobuf:"varint,1,opt,name=ProcessId,proto3" json:"ProcessId,omitempty"`
	FiberId       int64                  `protobuf:"varint,2,opt,name=FiberId,proto3" json:"FiberId,omitempty"`
	InstanceId    int64                  `protobuf:"varint,3,opt,name=InstanceId,proto3" json:"InstanceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorId) Reset() {
	*x = ActorId{}
	mi := &file_proto_lockstep_inner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorId) ProtoMessage() {}

func (x *ActorId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_inner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorId.ProtoReflect.Descriptor instead.
func (*ActorId) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_inner_proto_rawDescGZIP(), []int{0}
}

func (x *ActorId) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *ActorId) GetFiberId() int64 {
	if x != nil {
		return x.FiberId
	}
	return 0
}

func (x *ActorId) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type G2Match_Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *G2Match_Match) Reset() {
	*x = G2Match_Match{}
	mi := &file_proto_lockstep_inner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *G2Match_Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2Match_Match) ProtoMessage() {}

func (x *G2Match_Match) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_inner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2Match_Match.ProtoReflect.Descriptor instead.
func (*G2Match_Match) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_inner_proto_rawDescGZIP(), []int{1}
}

func (x *G2Match_Match) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *G2Match_Match) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type Match2G_NotifyMatchSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	MapActorId    int64                  `protobuf:"varint,2,opt,name=MapActorId,proto3" json:"MapActorId,omitempty"`
	RoomActorId   int64                  `protobuf:"varint,3,opt,name=RoomActorId,proto3" json:"RoomActorId,omitempty"`
	MapActor      *ActorId               `protobuf:"bytes,4,opt,name=MapActor,proto3" json:"MapActor,omitempty"`
	RoomActor     *ActorId               `protobuf:"bytes,5,opt,name=RoomActor,proto3" json:"RoomActor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match2G_NotifyMatchSuccess) Reset() {
	*x = Match2G_NotifyMatchSuccess{}
	mi := &file_proto_lockstep_inner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match2G_NotifyMatchSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match2G_NotifyMatchSuccess) ProtoMessage() {}

func (x *Match2G_NotifyMatchSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_inner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match2G_NotifyMatchSuccess.ProtoReflect.Descriptor instead.
func (*Match2G_NotifyMatchSuccess) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_inner_proto_rawDescGZIP(), []int{2}
}

func (x *Match2G_NotifyMatchSuccess) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Match2G_NotifyMatchSuccess) GetMapActorId() int64 {
	if x != nil {
		return x.MapActorId
	}
	return 0
}

func (x *Match2G_NotifyMatchSuccess) GetRoomActorId() int64 {
	if x != nil {
		return x.RoomActorId
	}
	return 0
}

func (x *Match2G_NotifyMatchSuccess) GetMapActor() *ActorId {
	if x != nil {
		return x.MapActor
	}
	return nil
}

func (x *Match2G_NotifyMatchSuccess) GetRoomActor() *ActorId {
	if x != nil {
		return x.RoomActor
	}
	return nil
}

type Room2M_NotifyRoomDispose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomActorId   int64                  `protobuf:"varint,1,opt,name=RoomActorId,proto3" json:"RoomActorId,omitempty"`
	PlayerIds     []int64                `protobuf:"varint,2,rep,packed,name=PlayerIds,proto3" json:"PlayerIds,omitempty"`
	DisposeAt     int64                  `protobuf:"varint,3,opt,name=DisposeAt,proto3" json:"DisposeAt,omitempty"`
	RoomActor     *ActorId               `protobuf:"bytes,4,opt,name=RoomActor,proto3" json:"RoomActor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room2M_NotifyRoomDispose) Reset() {
	*x = Room2M_NotifyRoomDispose{}
	mi := &file_proto_lockstep_inner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room2M_NotifyRoomDispose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room2M_NotifyRoomDispose) ProtoMessage() {}

func (x *Room2M_NotifyRoomDispose) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_inner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room2M_NotifyRoomDispose.ProtoReflect.Descriptor instead.
func (*Room2M_NotifyRoomDispose) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_inner_proto_rawDescGZIP(), []int{3}
}

func (x *Room2M_NotifyRoomDispose) GetRoomActorId() int64 {
	if x != nil {
		return x.RoomActorId
	}
	return 0
}

func (x *Room2M_NotifyRoomDispose) GetPlayerIds() []int64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *Room2M_NotifyRoomDispose) GetDisposeAt() int64 {
	if x != nil {
		return x.DisposeAt
	}
	return 0
}

func (x *Room2M_NotifyRoomDispose) GetRoomActor() *ActorId {
	if x != nil {
		return x.RoomActor
	}
	return nil
}

type G2Room_Reconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *G2Room_Reconnect) Reset() {
	*x = G2Room_Reconnect{}
	mi := &file_proto_lockstep_inner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *G2Room_Reconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2Room_Reconnect) ProtoMessage() {}

func (x *G2Room_Reconnect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_inner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2Room_Reconnect.ProtoReflect.Descriptor instead.
func (*G2Room_Reconnect) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_inner_proto_rawDescGZIP(), []int{4}
}

func (x *G2Room_Reconnect) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *G2Room_Reconnect) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type M2Room_PlayerOffline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2Room_PlayerOffline) Reset() {
	*x = M2Room_PlayerOffline{}
	mi := &file_proto_lockstep_inner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2Room_PlayerOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2Room_PlayerOffline) ProtoMessage() {}

func (x *M2Room_PlayerOffline) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_inner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2Room_PlayerOffline.ProtoReflect.Descriptor instead.
func (*M2Room_PlayerOffline) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_inner_proto_rawDescGZIP(), []int{5}
}

func (x *M2Room_PlayerOffline) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type Match2Map_CancelRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	RoomActor     *ActorId               `protobuf:"bytes,2,opt,name=RoomActor,proto3" json:"RoomActor,omitempty"`
	PlayerIds     []int64                `protobuf:"varint,3,rep,packed,name=PlayerIds,proto3" json:"PlayerIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match2Map_CancelRoom) Reset() {
	*x = Match2Map_CancelRoom{}
	mi := &file_proto_lockstep_inner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match2Map_CancelRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match2Map_CancelRoom) ProtoMessage() {}

func (x *Match2Map_CancelRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_inner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match2Map_CancelRoom.ProtoReflect.Descriptor instead.
func (*Match2Map_CancelRoom) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_inner_proto_rawDescGZIP(), []int{6}
}

func (x *Match2Map_CancelRoom) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *Match2Map_CancelRoom) GetRoomActor() *ActorId {
	if x != nil {
		return x.RoomActor
	}
	return nil
}

func (x *Match2Map_CancelRoom) GetPlayerIds() []int64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

type Map2Match_CancelRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Cancelled     bool                   `protobuf:"varint,2,opt,name=Cancelled,proto3" json:"Cancelled,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Map2Match_CancelRoom) Reset() {
	*x = Map2Match_CancelRoom{}
	mi := &file_proto_lockstep_inner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Map2Match_CancelRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map2Match_CancelRoom) ProtoMessage() {}

func (x *Map2Match_CancelRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_inner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map2Match_CancelRoom.ProtoReflect.Descriptor instead.
func (*Map2Match_CancelRoom) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_inner_proto_rawDescGZIP(), []int{7}
}

func (x *Map2Match_CancelRoom) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *Map2Match_CancelRoom) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *Map2Match_CancelRoom) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Match2G_CancelMatchSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	MapActor      *ActorId               `protobuf:"bytes,2,opt,name=MapActor,proto3" json:"MapActor,omitempty"`
	RoomActor     *ActorId               `protobuf:"bytes,3,opt,name=RoomActor,proto3" json:"RoomActor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match2G_CancelMatchSuccess) Reset() {
	*x = Match2G_CancelMatchSuccess{}
	mi := &file_proto_lockstep_inner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match2G_CancelMatchSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match2G_CancelMatchSuccess) ProtoMessage() {}

func (x *Match2G_CancelMatchSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lockstep_inner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match2G_CancelMatchSuccess.ProtoReflect.Descriptor instead.
func (*Match2G_CancelMatchSuccess) Descriptor() ([]byte, []int) {
	return file_proto_lockstep_inner_proto_rawDescGZIP(), []int{8}
}

func (x *Match2G_CancelMatchSuccess) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Match2G_CancelMatchSuccess) GetMapActor() *ActorId {
	if x != nil {
		return x.MapActor
	}
	return nil
}

func (x *Match2G_CancelMatchSuccess) GetRoomActor() *ActorId {
	if x != nil {
		return x.RoomActor
	}
	return nil
}

var File_proto_lockstep_inner_proto protoreflect.FileDescriptor

const file_proto_lockstep_inner_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/lockstep_inner.proto\x12\x13etgo.proto.lockstep\"a\n" +
	"\aActorId\x12\x1c\n" +
	"\tProcessId\x18\x01 \x01(\x05R\tProcessId\x12\x18\n" +
	"\aFiberId\x18\x02 \x01(\x03R\aFiberId\x12\x1e\n" +
	"\n" +
	"InstanceId\x18\x03 \x01(\x03R\n" +
	"InstanceId\"A\n" +
	"\rG2Match_Match\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1a\n" +
	"\bPlayerId\x18\x02 \x01(\x03R\bPlayerId\"\xf0\x01\n" +
	"\x1aMatch2G_NotifyMatchSuccess\x12\x1a\n" +
	"\bPlayerId\x18\x01 \x01(\x03R\bPlayerId\x12\x1e\n" +
	"\n" +
	"MapActorId\x18\x02 \x01(\x03R\n" +
	"MapActorId\x12 \n" +
	"\vRoomActorId\x18\x03 \x01(\x03R\vRoomActorId\x128\n" +
	"\bMapActor\x18\x04 \x01(\v2\x1c.etgo.proto.lockstep.ActorIdR\bMapActor\x12:\n" +
	"\tRoomActor\x18\x05 \x01(\v2\x1c.etgo.proto.lockstep.ActorIdR\tRoomActor\"\xb4\x01\n" +
	"\x18Room2M_NotifyRoomDispose\x12 \n" +
	"\vRoomActorId\x18\x01 \x01(\x03R\vRoomActorId\x12\x1c\n" +
	"\tPlayerIds\x18\x02 \x03(\x03R\tPlayerIds\x12\x1c\n" +
	"\tDisposeAt\x18\x03 \x01(\x03R\tDisposeAt\x12:\n" +
	"\tRoomActor\x18\x04 \x01(\v2\x1c.etgo.proto.lockstep.ActorIdR\tRoomActor\"D\n" +
	"\x10G2Room_Reconnect\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1a\n" +
	"\bPlayerId\x18\x02 \x01(\x03R\bPlayerId\"2\n" +
	"\x14M2Room_PlayerOffline\x12\x1a\n" +
	"\bPlayerId\x18\x01 \x01(\x03R\bPlayerId\"\x86\x01\n" +
	"\x14Match2Map_CancelRoom\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12:\n" +
	"\tRoomActor\x18\x02 \x01(\v2\x1c.etgo.proto.lockstep.ActorIdR\tRoomActor\x12\x1c\n" +
	"\tPlayerIds\x18\x03 \x03(\x03R\tPlayerIds\"d\n" +
	"\x14Map2Match_CancelRoom\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1c\n" +
	"\tCancelled\x18\x02 \x01(\bR\tCancelled\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\"\xae\x01\n" +
	"\x1aMatch2G_CancelMatchSuccess\x12\x1a\n" +
	"\bPlayerId\x18\x01 \x01(\x03R\bPlayerId\x128\n" +
	"\bMapActor\x18\x02 \x01(\v2\x1c.etgo.proto.lockstep.ActorIdR\bMapActor\x12:\n" +
	"\tRoomActor\x18\x03 \x01(\v2\x1c.etgo.proto.lockstep.ActorIdR\tRoomActorB4Z2github.com/jerbe/et-go/proto/locksteppb;locksteppbb\x06proto3"

var (
	file_proto_lockstep_inner_proto_rawDescOnce sync.Once
	file_proto_lockstep_inner_proto_rawDescData []byte
)

func file_proto_lockstep_inner_proto_rawDescGZIP() []byte {
	file_proto_lockstep_inner_proto_rawDescOnce.Do(func() {
		file_proto_lockstep_inner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lockstep_inner_proto_rawDesc), len(file_proto_lockstep_inner_proto_rawDesc)))
	})
	return file_proto_lockstep_inner_proto_rawDescData
}

var file_proto_lockstep_inner_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_lockstep_inner_proto_goTypes = []any{
	(*ActorId)(nil),                    // 0: etgo.proto.lockstep.ActorId
	(*G2Match_Match)(nil),              // 1: etgo.proto.lockstep.G2Match_Match
	(*Match2G_NotifyMatchSuccess)(nil), // 2: etgo.proto.lockstep.Match2G_NotifyMatchSuccess
	(*Room2M_NotifyRoomDispose)(nil),   // 3: etgo.proto.lockstep.Room2M_NotifyRoomDispose
	(*G2Room_Reconnect)(nil),           // 4: etgo.proto.lockstep.G2Room_Reconnect
	(*M2Room_PlayerOffline)(nil),       // 5: etgo.proto.lockstep.M2Room_PlayerOffline
	(*Match2Map_CancelRoom)(nil),       // 6: etgo.proto.lockstep.Match2Map_CancelRoom
	(*Map2Match_CancelRoom)(nil),       // 7: etgo.proto.lockstep.Map2Match_CancelRoom
	(*Match2G_CancelMatchSuccess)(nil), // 8: etgo.proto.lockstep.Match2G_CancelMatchSuccess
}
var file_proto_lockstep_inner_proto_depIdxs = []int32{
	0, // 0: etgo.proto.lockstep.Match2G_NotifyMatchSuccess.MapActor:type_name -> etgo.proto.lockstep.ActorId
	0, // 1: etgo.proto.lockstep.Match2G_NotifyMatchSuccess.RoomActor:type_name -> etgo.proto.lockstep.ActorId
	0, // 2: etgo.proto.lockstep.Room2M_NotifyRoomDispose.RoomActor:type_name -> etgo.proto.lockstep.ActorId
	0, // 3: etgo.proto.lockstep.Match2Map_CancelRoom.RoomActor:type_name -> etgo.proto.lockstep.ActorId
	0, // 4: etgo.proto.lockstep.Match2G_CancelMatchSuccess.MapActor:type_name -> etgo.proto.lockstep.ActorId
	0, // 5: etgo.proto.lockstep.Match2G_CancelMatchSuccess.RoomActor:type_name -> etgo.proto.lockstep.ActorId
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_lockstep_inner_proto_init() }
func file_proto_lockstep_inner_proto_init() {
	if File_proto_lockstep_inner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lockstep_inner_proto_rawDesc), len(file_proto_lockstep_inner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_lockstep_inner_proto_goTypes,
		DependencyIndexes: file_proto_lockstep_inner_proto_depIdxs,
		MessageInfos:      file_proto_lockstep_inner_proto_msgTypes,
	}.Build()
	File_proto_lockstep_inner_proto = out.File
	file_proto_lockstep_inner_proto_goTypes = nil
	file_proto_lockstep_inner_proto_depIdxs = nil
}
