// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/map_inner.proto

package mapinnerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     int32                  `protobuf:"varint,1,opt,name=ProcessId,proto3" json:"ProcessId,omitempty"`
	FiberId       int64                  `protobuf:"varint,2,opt,name=FiberId,proto3" json:"FiberId,omitempty"`
	InstanceId    int64                  `protobuf:"varint,3,opt,name=InstanceId,proto3" json:"InstanceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorId) Reset() {
	*x = ActorId{}
	mi := &file_proto_map_inner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorId) ProtoMessage() {}

func (x *ActorId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_inner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorId.ProtoReflect.Descriptor instead.
func (*ActorId) Descriptor() ([]byte, []int) {
	return file_proto_map_inner_proto_rawDescGZIP(), []int{0}
}

func (x *ActorId) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *ActorId) GetFiberId() int64 {
	if x != nil {
		return x.FiberId
	}
	return 0
}

func (x *ActorId) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type G2M_EnterMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *G2M_EnterMap) Reset() {
	*x = G2M_EnterMap{}
	mi := &file_proto_map_inner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *G2M_EnterMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2M_EnterMap) ProtoMessage() {}

func (x *G2M_EnterMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_inner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2M_EnterMap.ProtoReflect.Descriptor instead.
func (*G2M_EnterMap) Descriptor() ([]byte, []int) {
	return file_proto_map_inner_proto_rawDescGZIP(), []int{1}
}

func (x *G2M_EnterMap) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *G2M_EnterMap) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type M2G_EnterMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2G_EnterMap) Reset() {
	*x = M2G_EnterMap{}
	mi := &file_proto_map_inner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2G_EnterMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2G_EnterMap) ProtoMessage() {}

func (x *M2G_EnterMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_inner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2G_EnterMap.ProtoReflect.Descriptor instead.
func (*M2G_EnterMap) Descriptor() ([]byte, []int) {
	return file_proto_map_inner_proto_rawDescGZIP(), []int{2}
}

func (x *M2G_EnterMap) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *M2G_EnterMap) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *M2G_EnterMap) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type M2M_UnitTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	OldActorId    *ActorId               `protobuf:"bytes,2,opt,name=OldActorId,proto3" json:"OldActorId,omitempty"`
	Unit          []byte                 `protobuf:"bytes,3,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Entitys       [][]byte               `protobuf:"bytes,4,rep,name=Entitys,proto3" json:"Entitys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2M_UnitTransferRequest) Reset() {
	*x = M2M_UnitTransferRequest{}
	mi := &file_proto_map_inner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2M_UnitTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2M_UnitTransferRequest) ProtoMessage() {}

func (x *M2M_UnitTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_inner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2M_UnitTransferRequest.ProtoReflect.Descriptor instead.
func (*M2M_UnitTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_map_inner_proto_rawDescGZIP(), []int{3}
}

func (x *M2M_UnitTransferRequest) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *M2M_UnitTransferRequest) GetOldActorId() *ActorId {
	if x != nil {
		return x.OldActorId
	}
	return nil
}

func (x *M2M_UnitTransferRequest) GetUnit() []byte {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *M2M_UnitTransferRequest) GetEntitys() [][]byte {
	if x != nil {
		return x.Entitys
	}
	return nil
}

type M2M_UnitTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2M_UnitTransferResponse) Reset() {
	*x = M2M_UnitTransferResponse{}
	mi := &file_proto_map_inner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2M_UnitTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2M_UnitTransferResponse) ProtoMessage() {}

func (x *M2M_UnitTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_map_inner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2M_UnitTransferResponse.ProtoReflect.Descriptor instead.
func (*M2M_UnitTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_map_inner_proto_rawDescGZIP(), []int{4}
}

func (x *M2M_UnitTransferResponse) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *M2M_UnitTransferResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *M2M_UnitTransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_map_inner_proto protoreflect.FileDescriptor

const file_proto_map_inner_proto_rawDesc = "" +
	"\n" +
	"\x15proto/map_inner.proto\x12\x05proto\"a\n" +
	"\aActorId\x12\x1c\n" +
	"\tProcessId\x18\x01 \x01(\x05R\tProcessId\x12\x18\n" +
	"\aFiberId\x18\x02 \x01(\x03R\aFiberId\x12\x1e\n" +
	"\n" +
	"InstanceId\x18\x03 \x01(\x03R\n" +
	"InstanceId\"@\n" +
	"\fG2M_EnterMap\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x1a\n" +
	"\bPlayerId\x18\x02 \x01(\x03R\bPlayerId\"T\n" +
	"\fM2G_EnterMap\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\"\x8d\x01\n" +
	"\x17M2M_UnitTransferRequest\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12.\n" +
	"\n" +
	"OldActorId\x18\x02 \x01(\v2\x0e.proto.ActorIdR\n" +
	"OldActorId\x12\x12\n" +
	"\x04Unit\x18\x03 \x01(\fR\x04Unit\x12\x18\n" +
	"\aEntitys\x18\x04 \x03(\fR\aEntitys\"`\n" +
	"\x18M2M_UnitTransferResponse\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessageB4Z2github.com/jerbe/et-go/proto/mapinnerpb;mapinnerpbb\x06proto3"

var (
	file_proto_map_inner_proto_rawDescOnce sync.Once
	file_proto_map_inner_proto_rawDescData []byte
)

func file_proto_map_inner_proto_rawDescGZIP() []byte {
	file_proto_map_inner_proto_rawDescOnce.Do(func() {
		file_proto_map_inner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_map_inner_proto_rawDesc), len(file_proto_map_inner_proto_rawDesc)))
	})
	return file_proto_map_inner_proto_rawDescData
}

var file_proto_map_inner_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_map_inner_proto_goTypes = []any{
	(*ActorId)(nil),                  // 0: proto.ActorId
	(*G2M_EnterMap)(nil),             // 1: proto.G2M_EnterMap
	(*M2G_EnterMap)(nil),             // 2: proto.M2G_EnterMap
	(*M2M_UnitTransferRequest)(nil),  // 3: proto.M2M_UnitTransferRequest
	(*M2M_UnitTransferResponse)(nil), // 4: proto.M2M_UnitTransferResponse
}
var file_proto_map_inner_proto_depIdxs = []int32{
	0, // 0: proto.M2M_UnitTransferRequest.OldActorId:type_name -> proto.ActorId
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_map_inner_proto_init() }
func file_proto_map_inner_proto_init() {
	if File_proto_map_inner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_map_inner_proto_rawDesc), len(file_proto_map_inner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_map_inner_proto_goTypes,
		DependencyIndexes: file_proto_map_inner_proto_depIdxs,
		MessageInfos:      file_proto_map_inner_proto_msgTypes,
	}.Build()
	File_proto_map_inner_proto = out.File
	file_proto_map_inner_proto_goTypes = nil
	file_proto_map_inner_proto_depIdxs = nil
}
