// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/inventory_outer.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	ConfigId      int32                  `protobuf:"varint,2,opt,name=ConfigId,proto3" json:"ConfigId,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,4,opt,name=SlotIndex,proto3" json:"SlotIndex,omitempty"`
	UniqueId      int64                  `protobuf:"varint,5,opt,name=UniqueId,proto3" json:"UniqueId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_proto_inventory_outer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_outer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_proto_inventory_outer_proto_rawDescGZIP(), []int{0}
}

func (x *ItemInfo) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemInfo) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ItemInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemInfo) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *ItemInfo) GetUniqueId() int64 {
	if x != nil {
		return x.UniqueId
	}
	return 0
}

type C2M_GetBagInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	UnitId        int64                  `protobuf:"varint,2,opt,name=UnitId,proto3" json:"UnitId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2M_GetBagInfo) Reset() {
	*x = C2M_GetBagInfo{}
	mi := &file_proto_inventory_outer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2M_GetBagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2M_GetBagInfo) ProtoMessage() {}

func (x *C2M_GetBagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_outer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2M_GetBagInfo.ProtoReflect.Descriptor instead.
func (*C2M_GetBagInfo) Descriptor() ([]byte, []int) {
	return file_proto_inventory_outer_proto_rawDescGZIP(), []int{1}
}

func (x *C2M_GetBagInfo) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *C2M_GetBagInfo) GetUnitId() int64 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

type M2C_GetBagInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	MaxCapacity   int32                  `protobuf:"varint,4,opt,name=MaxCapacity,proto3" json:"MaxCapacity,omitempty"`
	Items         []*ItemInfo            `protobuf:"bytes,5,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2C_GetBagInfo) Reset() {
	*x = M2C_GetBagInfo{}
	mi := &file_proto_inventory_outer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_GetBagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_GetBagInfo) ProtoMessage() {}

func (x *M2C_GetBagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_outer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_GetBagInfo.ProtoReflect.Descriptor instead.
func (*M2C_GetBagInfo) Descriptor() ([]byte, []int) {
	return file_proto_inventory_outer_proto_rawDescGZIP(), []int{2}
}

func (x *M2C_GetBagInfo) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *M2C_GetBagInfo) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *M2C_GetBagInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *M2C_GetBagInfo) GetMaxCapacity() int32 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

func (x *M2C_GetBagInfo) GetItems() []*ItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type C2M_BagOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	UnitId        int64                  `protobuf:"varint,2,opt,name=UnitId,proto3" json:"UnitId,omitempty"`
	OpType        int32                  `protobuf:"varint,3,opt,name=OpType,proto3" json:"OpType,omitempty"`
	ItemId        int64                  `protobuf:"varint,4,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	ConfigId      int32                  `protobuf:"varint,5,opt,name=ConfigId,proto3" json:"ConfigId,omitempty"`
	Count         int32                  `protobuf:"varint,6,opt,name=Count,proto3" json:"Count,omitempty"`
	SourceSlot    int32                  `protobuf:"varint,7,opt,name=SourceSlot,proto3" json:"SourceSlot,omitempty"`
	TargetSlot    int32                  `protobuf:"varint,8,opt,name=TargetSlot,proto3" json:"TargetSlot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2M_BagOperation) Reset() {
	*x = C2M_BagOperation{}
	mi := &file_proto_inventory_outer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2M_BagOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2M_BagOperation) ProtoMessage() {}

func (x *C2M_BagOperation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_outer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2M_BagOperation.ProtoReflect.Descriptor instead.
func (*C2M_BagOperation) Descriptor() ([]byte, []int) {
	return file_proto_inventory_outer_proto_rawDescGZIP(), []int{3}
}

func (x *C2M_BagOperation) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *C2M_BagOperation) GetUnitId() int64 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *C2M_BagOperation) GetOpType() int32 {
	if x != nil {
		return x.OpType
	}
	return 0
}

func (x *C2M_BagOperation) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *C2M_BagOperation) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *C2M_BagOperation) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *C2M_BagOperation) GetSourceSlot() int32 {
	if x != nil {
		return x.SourceSlot
	}
	return 0
}

func (x *C2M_BagOperation) GetTargetSlot() int32 {
	if x != nil {
		return x.TargetSlot
	}
	return 0
}

type M2C_BagOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2C_BagOperation) Reset() {
	*x = M2C_BagOperation{}
	mi := &file_proto_inventory_outer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_BagOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_BagOperation) ProtoMessage() {}

func (x *M2C_BagOperation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_outer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_BagOperation.ProtoReflect.Descriptor instead.
func (*M2C_BagOperation) Descriptor() ([]byte, []int) {
	return file_proto_inventory_outer_proto_rawDescGZIP(), []int{4}
}

func (x *M2C_BagOperation) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *M2C_BagOperation) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *M2C_BagOperation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type C2M_GetWarehouseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	UnitId        int64                  `protobuf:"varint,2,opt,name=UnitId,proto3" json:"UnitId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2M_GetWarehouseInfo) Reset() {
	*x = C2M_GetWarehouseInfo{}
	mi := &file_proto_inventory_outer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2M_GetWarehouseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2M_GetWarehouseInfo) ProtoMessage() {}

func (x *C2M_GetWarehouseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_outer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2M_GetWarehouseInfo.ProtoReflect.Descriptor instead.
func (*C2M_GetWarehouseInfo) Descriptor() ([]byte, []int) {
	return file_proto_inventory_outer_proto_rawDescGZIP(), []int{5}
}

func (x *C2M_GetWarehouseInfo) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *C2M_GetWarehouseInfo) GetUnitId() int64 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

type M2C_GetWarehouseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	MaxCapacity   int32                  `protobuf:"varint,4,opt,name=MaxCapacity,proto3" json:"MaxCapacity,omitempty"`
	Items         []*ItemInfo            `protobuf:"bytes,5,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2C_GetWarehouseInfo) Reset() {
	*x = M2C_GetWarehouseInfo{}
	mi := &file_proto_inventory_outer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_GetWarehouseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_GetWarehouseInfo) ProtoMessage() {}

func (x *M2C_GetWarehouseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_outer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_GetWarehouseInfo.ProtoReflect.Descriptor instead.
func (*M2C_GetWarehouseInfo) Descriptor() ([]byte, []int) {
	return file_proto_inventory_outer_proto_rawDescGZIP(), []int{6}
}

func (x *M2C_GetWarehouseInfo) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *M2C_GetWarehouseInfo) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *M2C_GetWarehouseInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *M2C_GetWarehouseInfo) GetMaxCapacity() int32 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

func (x *M2C_GetWarehouseInfo) GetItems() []*ItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type C2M_WarehouseOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	UnitId        int64                  `protobuf:"varint,2,opt,name=UnitId,proto3" json:"UnitId,omitempty"`
	OpType        int32                  `protobuf:"varint,3,opt,name=OpType,proto3" json:"OpType,omitempty"`
	ItemId        int64                  `protobuf:"varint,4,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=Count,proto3" json:"Count,omitempty"`
	SourceSlot    int32                  `protobuf:"varint,6,opt,name=SourceSlot,proto3" json:"SourceSlot,omitempty"`
	TargetSlot    int32                  `protobuf:"varint,7,opt,name=TargetSlot,proto3" json:"TargetSlot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2M_WarehouseOperation) Reset() {
	*x = C2M_WarehouseOperation{}
	mi := &file_proto_inventory_outer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2M_WarehouseOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2M_WarehouseOperation) ProtoMessage() {}

func (x *C2M_WarehouseOperation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_outer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2M_WarehouseOperation.ProtoReflect.Descriptor instead.
func (*C2M_WarehouseOperation) Descriptor() ([]byte, []int) {
	return file_proto_inventory_outer_proto_rawDescGZIP(), []int{7}
}

func (x *C2M_WarehouseOperation) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *C2M_WarehouseOperation) GetUnitId() int64 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *C2M_WarehouseOperation) GetOpType() int32 {
	if x != nil {
		return x.OpType
	}
	return 0
}

func (x *C2M_WarehouseOperation) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *C2M_WarehouseOperation) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *C2M_WarehouseOperation) GetSourceSlot() int32 {
	if x != nil {
		return x.SourceSlot
	}
	return 0
}

func (x *C2M_WarehouseOperation) GetTargetSlot() int32 {
	if x != nil {
		return x.TargetSlot
	}
	return 0
}

type M2C_WarehouseOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcId         uint32                 `protobuf:"varint,1,opt,name=RpcId,proto3" json:"RpcId,omitempty"`
	Error         int32                  `protobuf:"varint,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2C_WarehouseOperation) Reset() {
	*x = M2C_WarehouseOperation{}
	mi := &file_proto_inventory_outer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_WarehouseOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_WarehouseOperation) ProtoMessage() {}

func (x *M2C_WarehouseOperation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_outer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_WarehouseOperation.ProtoReflect.Descriptor instead.
func (*M2C_WarehouseOperation) Descriptor() ([]byte, []int) {
	return file_proto_inventory_outer_proto_rawDescGZIP(), []int{8}
}

func (x *M2C_WarehouseOperation) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *M2C_WarehouseOperation) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *M2C_WarehouseOperation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type M2C_ItemChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    int32                  `protobuf:"varint,1,opt,name=ChangeType,proto3" json:"ChangeType,omitempty"`
	Container     int32                  `protobuf:"varint,2,opt,name=Container,proto3" json:"Container,omitempty"`
	Item          *ItemInfo              `protobuf:"bytes,3,opt,name=Item,proto3" json:"Item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M2C_ItemChange) Reset() {
	*x = M2C_ItemChange{}
	mi := &file_proto_inventory_outer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M2C_ItemChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M2C_ItemChange) ProtoMessage() {}

func (x *M2C_ItemChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_outer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M2C_ItemChange.ProtoReflect.Descriptor instead.
func (*M2C_ItemChange) Descriptor() ([]byte, []int) {
	return file_proto_inventory_outer_proto_rawDescGZIP(), []int{9}
}

func (x *M2C_ItemChange) GetChangeType() int32 {
	if x != nil {
		return x.ChangeType
	}
	return 0
}

func (x *M2C_ItemChange) GetContainer() int32 {
	if x != nil {
		return x.Container
	}
	return 0
}

func (x *M2C_ItemChange) GetItem() *ItemInfo {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_proto_inventory_outer_proto protoreflect.FileDescriptor

const file_proto_inventory_outer_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/inventory_outer.proto\x12\x05proto\"\x8e\x01\n" +
	"\bItemInfo\x12\x16\n" +
	"\x06ItemId\x18\x01 \x01(\x03R\x06ItemId\x12\x1a\n" +
	"\bConfigId\x18\x02 \x01(\x05R\bConfigId\x12\x14\n" +
	"\x05Count\x18\x03 \x01(\x05R\x05Count\x12\x1c\n" +
	"\tSlotIndex\x18\x04 \x01(\x05R\tSlotIndex\x12\x1a\n" +
	"\bUniqueId\x18\x05 \x01(\x03R\bUniqueId\">\n" +
	"\x0eC2M_GetBagInfo\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x16\n" +
	"\x06UnitId\x18\x02 \x01(\x03R\x06UnitId\"\x9f\x01\n" +
	"\x0eM2C_GetBagInfo\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\x12 \n" +
	"\vMaxCapacity\x18\x04 \x01(\x05R\vMaxCapacity\x12%\n" +
	"\x05Items\x18\x05 \x03(\v2\x0f.proto.ItemInfoR\x05Items\"\xe2\x01\n" +
	"\x10C2M_BagOperation\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x16\n" +
	"\x06UnitId\x18\x02 \x01(\x03R\x06UnitId\x12\x16\n" +
	"\x06OpType\x18\x03 \x01(\x05R\x06OpType\x12\x16\n" +
	"\x06ItemId\x18\x04 \x01(\x03R\x06ItemId\x12\x1a\n" +
	"\bConfigId\x18\x05 \x01(\x05R\bConfigId\x12\x14\n" +
	"\x05Count\x18\x06 \x01(\x05R\x05Count\x12\x1e\n" +
	"\n" +
	"SourceSlot\x18\a \x01(\x05R\n" +
	"SourceSlot\x12\x1e\n" +
	"\n" +
	"TargetSlot\x18\b \x01(\x05R\n" +
	"TargetSlot\"X\n" +
	"\x10M2C_BagOperation\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\"D\n" +
	"\x14C2M_GetWarehouseInfo\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x16\n" +
	"\x06UnitId\x18\x02 \x01(\x03R\x06UnitId\"\xa5\x01\n" +
	"\x14M2C_GetWarehouseInfo\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\x12 \n" +
	"\vMaxCapacity\x18\x04 \x01(\x05R\vMaxCapacity\x12%\n" +
	"\x05Items\x18\x05 \x03(\v2\x0f.proto.ItemInfoR\x05Items\"\xcc\x01\n" +
	"\x16C2M_WarehouseOperation\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x16\n" +
	"\x06UnitId\x18\x02 \x01(\x03R\x06UnitId\x12\x16\n" +
	"\x06OpType\x18\x03 \x01(\x05R\x06OpType\x12\x16\n" +
	"\x06ItemId\x18\x04 \x01(\x03R\x06ItemId\x12\x14\n" +
	"\x05Count\x18\x05 \x01(\x05R\x05Count\x12\x1e\n" +
	"\n" +
	"SourceSlot\x18\x06 \x01(\x05R\n" +
	"SourceSlot\x12\x1e\n" +
	"\n" +
	"TargetSlot\x18\a \x01(\x05R\n" +
	"TargetSlot\"^\n" +
	"\x16M2C_WarehouseOperation\x12\x14\n" +
	"\x05RpcId\x18\x01 \x01(\rR\x05RpcId\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\x05R\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\"s\n" +
	"\x0eM2C_ItemChange\x12\x1e\n" +
	"\n" +
	"ChangeType\x18\x01 \x01(\x05R\n" +
	"ChangeType\x12\x1c\n" +
	"\tContainer\x18\x02 \x01(\x05R\tContainer\x12#\n" +
	"\x04Item\x18\x03 \x01(\v2\x0f.proto.ItemInfoR\x04ItemB6Z4github.com/jerbe/et-go/proto/inventorypb;inventorypbb\x06proto3"

var (
	file_proto_inventory_outer_proto_rawDescOnce sync.Once
	file_proto_inventory_outer_proto_rawDescData []byte
)

func file_proto_inventory_outer_proto_rawDescGZIP() []byte {
	file_proto_inventory_outer_proto_rawDescOnce.Do(func() {
		file_proto_inventory_outer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_outer_proto_rawDesc), len(file_proto_inventory_outer_proto_rawDesc)))
	})
	return file_proto_inventory_outer_proto_rawDescData
}

var file_proto_inventory_outer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_inventory_outer_proto_goTypes = []any{
	(*ItemInfo)(nil),               // 0: proto.ItemInfo
	(*C2M_GetBagInfo)(nil),         // 1: proto.C2M_GetBagInfo
	(*M2C_GetBagInfo)(nil),         // 2: proto.M2C_GetBagInfo
	(*C2M_BagOperation)(nil),       // 3: proto.C2M_BagOperation
	(*M2C_BagOperation)(nil),       // 4: proto.M2C_BagOperation
	(*C2M_GetWarehouseInfo)(nil),   // 5: proto.C2M_GetWarehouseInfo
	(*M2C_GetWarehouseInfo)(nil),   // 6: proto.M2C_GetWarehouseInfo
	(*C2M_WarehouseOperation)(nil), // 7: proto.C2M_WarehouseOperation
	(*M2C_WarehouseOperation)(nil), // 8: proto.M2C_WarehouseOperation
	(*M2C_ItemChange)(nil),         // 9: proto.M2C_ItemChange
}
var file_proto_inventory_outer_proto_depIdxs = []int32{
	0, // 0: proto.M2C_GetBagInfo.Items:type_name -> proto.ItemInfo
	0, // 1: proto.M2C_GetWarehouseInfo.Items:type_name -> proto.ItemInfo
	0, // 2: proto.M2C_ItemChange.Item:type_name -> proto.ItemInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_inventory_outer_proto_init() }
func file_proto_inventory_outer_proto_init() {
	if File_proto_inventory_outer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_outer_proto_rawDesc), len(file_proto_inventory_outer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_inventory_outer_proto_goTypes,
		DependencyIndexes: file_proto_inventory_outer_proto_depIdxs,
		MessageInfos:      file_proto_inventory_outer_proto_msgTypes,
	}.Build()
	File_proto_inventory_outer_proto = out.File
	file_proto_inventory_outer_proto_goTypes = nil
	file_proto_inventory_outer_proto_depIdxs = nil
}
